var blues = {
"01001":{"count": 46, "artists":['Poonanny']},
"01015":{"count": 30, "artists":['Rosetta Tharpe', 'Lucky Millinder']},
"01017":{"count": 41, "artists":['Razzy Bailey']},
"01043":{"count": 42, "artists":['Candi Staton']},
"01055":{"count": 7, "artists":['Jerry Boogie McCain']},
"01073":{"count": 71, "artists":['Taylor Hicks', 'ERSKINE HAWKINS', 'Erskine Hawkins & Orchestra', 'Keri Leigh']},
"01093":{"count": 41, "artists":['Sonny James']},
"01097":{"count": 2, "artists":['Jody Williams']},
"01101":{"count": 147, "artists":['Dr Feelgood', 'Big Mama Thornton with Kansas Bill and his Orchestra', 'Willie Mae "Big Mama" Thornton', 'Big Mama Thornton']},
"01103":{"count": 48, "artists":['Earl Gaines', 'The Sam Lay Blues Band', 'Palmera']},
"01119":{"count": 23, "artists":['Jaybird Coleman & Birmingham Jug Band', 'Jaybird Coleman']},
"01121":{"count": 32, "artists":['Five Blind Boys', 'Five Blind Boys of Alabama', 'The Five Blind Boys Of Alabama']},
"02090":{"count": 13, "artists":['Rick Holmstrom']},
"02170":{"count": 4, "artists":['Tito & Tarantula', 'Tito And Tarantula']},
"04019":{"count": 45, "artists":['Friends Of Dean Martinez']},
"04025":{"count": 15, "artists":['H.e.a.t']},
"05019":{"count": 94, "artists":['Wilbur deParis_ Jimmy Witherspoon', 'Jimmy Witherspoon / Robben Ford', 'Jay McShann_ Jimmy Witherspoon', 'Jimmy Witherspoon']},
"05027":{"count": 12, "artists":['Larry McCray']},
"05035":{"count": 91, "artists":['Johnnie Taylor and the Highway QCs', 'Johnnie Taylor', 'The Soul Stirrers']},
"05047":{"count": 45, "artists":['Roy Buchanan']},
"05063":{"count": 2, "artists":['Ollie Nightingale']},
"05067":{"count": 49, "artists":['Frank Frost & Sam Carr', 'Frank Frost']},
"05075":{"count": 83, "artists":['Washboard Sam']},
"05077":{"count": 34, "artists":['Floyd Jones', 'Detroit Junior']},
"05091":{"count": 15, "artists":['Buster Benton']},
"05095":{"count": 51, "artists":['Louis Jordan with Johnny Otis Featuring Shuggie Otis', 'LOUIS JORDAN', 'Louis Jordan & His Tympani Five', 'Jordan_ Louis', 'Louis Jordan & His Tympany Five']},
"05107":{"count": 53, "artists":['Cedell Davis', 'Robert Lockwood Jr', 'Robert Lockwood_ Jr.', 'Robert Lockwood Jr.', 'Willie "Big Eyes" Smith']},
"05117":{"count": 25, "artists":['Arbee Stidham']},
"05119":{"count": 226, "artists":['Roosevelt Sykes', 'Bill Casey Weldon', 'Casey Bill Weldon', 'Jack Williams_ Eleanor Williams_ David Winters', 'Jack Williams / Eleanor Williams / David Winters', 'Charley Jordon', 'Charley Jordan', 'Tony Spinner']},
"05123":{"count": 44, "artists":['Stavely Makepeace', 'Luther Allison']},
"05139":{"count": 53, "artists":['Al Caiola', 'Jesse James', 'The Ambassador Duo', 'Jack Livingston Marching Band', 'Robert Lowery']},
"05147":{"count": 15, "artists":['Roy Brown', 'Little Johnny Taylor', 'Little Jimmy Taylor']},
"06001":{"count": 87, "artists":['The Answer', 'Oversol', 'Gun', 'Gun & Gore', 'Sir Thomas Allen/Geoffrey Parsons', 'Alvin Youngblood Hart']},
"06019":{"count": 36, "artists":['Ian Moore', 'Ian Moore_ Lossy Coils', 'Doc Holliday', 'Steve White', 'Jimbo Ross']},
"06037":{"count": 1172, "artists":['The Doobie Brothers', 'Bill Withers', 'The Gunclub', 'Canned Heat And John Lee Hooker', 'Carl Anton/Hans Wahlgrens Orkester', 'Canned Heat', 'Little Feat', 'Little Feat (With Linda Ronstadt)', 'Glenn Hughes', 'Ritchie Valens', "Keb'Mo'", "Keb' Mo';Peter Maffay", 'Breakout', 'Shuggie Otis', "Elmer Gantry's Velvet Opera", 'Niacin', 'Steve Lukather', 'Ira Maria Witoschynskyj', 'Coco Montoya', 'Elvin Bishop', 'Bob Welch', 'Emitt Rhodes', 'Mable John / Sammy Ward', 'Mable John', 'Debbie Davies_ Chris Layton & Tommy Shannon', 'Little Caesar', 'Rod Piazza & The Mighty Flyers', 'Kirk Fletcher', 'Philip Sayce', 'The Premiers', 'Darren Smith', 'Smiley Lewis', 'Lewis_ Smiley', 'Phantom Blues Band', 'Big Jay McNeely', 'Big Jay Mc Neely', 'Amar Kobbi', 'Soulution', 'The Mannish Boys', 'William Clarke', 'Interstate Blues', 'Finis Tasby', 'Gun Club', 'The Gun Club', 'Snakefarm', 'Buddy Ace', 'Melora Hardin', 'Magnatune Compilation', "Keb' Mo'", 'Kane', 'The Nightwatchman', 'Debbie Davies', 'Bugs Henderson & The Shuffle Kings', 'Blue Stew', 'Joe Turner']},
"06045":{"count": 77, "artists":['Robben Ford', 'Robben Ford / Susan Tedeschi']},
"06065":{"count": 14, "artists":['Rod Piazza']},
"06067":{"count": 11, "artists":['Nil Lara']},
"06073":{"count": 13, "artists":['Lesser']},
"06075":{"count": 453, "artists":['Santana featuring Mana', 'Sisa', 'Mr. Vyrus', 'Santana featuring Eric Clapton', 'Santana Featuring Chad Kroeger', 'Santana Feat. Rob Thomas', 'Big Brother & The Holding Company (featuring Janis Joplin)', 'Big Brother & The Holding Company', 'Big Brother / The Holding Company', 'Big Brother & The Holding Company;Janis Joplin', 'Janis Joplin', 'DJ Mindforce', 'Quicksilver Messenger Service', 'Hot Tuna', 'Joe Louis Walker', 'Santana', 'J Church', 'Ride The Blinds', 'Sugar Pie De Santo', 'Sugar Pie DeSanto', 'The Jackie Payne-Steve Edmonson Band', 'Jolie Holland', 'Farlow-Kirch Band']},
"06085":{"count": 87, "artists":['Tommy Castro', 'Chris Cain']},
"06103":{"count": 87, "artists":['Robert Shaw;Grant Williams;The Robert Shaw Chorale', 'Robert Shaw Chorale and Orchestra;Robert Conant;Robert Arnold;Florence Kopleff;Richard Lewis', 'Robert Shaw;Robert Conant;Robert Arnold;Florence Kopleff;Richard Lewis', 'Robert Shaw', 'Robert Shaw;The Robert Shaw Chorale', 'Robert Shaw;Florence Kopleff;The Robert Shaw Chorale', 'Robert Shaw;Judith Raskin;Florence Kopleff;Richard Lewis;Thomas Paul;Robert Conant;Robert Arnold', 'Robert Shaw;Judith Raskin;Florence Kopleff;Richard Lewis;Thomas Paul;Robert Conant;Robert Arnold;James Smith', 'Robert Shaw;Thomas Pyle']},
"08031":{"count": 47, "artists":['Corey Harris']},
"08093":{"count": 25, "artists":['Rising Sons']},
"09001":{"count": 21, "artists":['Eric Von Schmidt']},
"09009":{"count": 49, "artists":['Mark Hummel', 'The Detergents']},
"10003":{"count": 94, "artists":['George Thorogood & The Destroyers', 'George Thorogood And The Destroyers', 'George Thorogood', 'Cisco Houston']},
"11001":{"count": 110, "artists":['Alice Stuart', 'Duck Baker', "John Lee 'Sonny Boy' Williamson", 'Buster Brown', 'Warner Williams and Jay Summerour']},
"12031":{"count": 102, "artists":['Blind Blake & The Royal Victoria Hotel Calypsos', 'Blind Blake', 'Jelly Roll Morton_ Johnny Dodds_ Blind Blake_ Jimmy Bertrand']},
"12033":{"count": 17, "artists":['Benny Spellman']},
"12057":{"count": 16, "artists":['Blues Image']},
"12105":{"count": 127, "artists":['Chris Bailey', 'Sticks & Stones', 'Rusty Tromble & The Sanchez Six', 'Dick Clark', 'Albert Castiglia', 'Eric Steckel', 'David Brinston', 'Tina Britt', 'Benny Latimore', 'Chuck Roberson', 'Mystro']},
"13021":{"count": 50, "artists":['Lucille Hegamin', 'Lucille Hegamin  ']},
"13063":{"count": 81, "artists":['Jesse Fuller']},
"13121":{"count": 96, "artists":['Young Jules', 'Brainbox', 'Chuck Willis & His Orchestra; featuring Freddy Jackson On Tenor Sax_ arrangements by Leroy Kirkland', 'Chuck Willis', 'Chuck Willis with The Royals', 'Titus Turner', 'Big Maceo Merriweather', 'Big Maceo']},
"13127":{"count": 57, "artists":['Bumble Bee Slim']},
"13177":{"count": 85, "artists":['Tampa Red']},
"13189":{"count": 88, "artists":['Blind Willie', 'Ruth Willis', 'Blind Willie & Partner', 'Blind Willie McTell_ Ruth Willis', 'Blind Samie', 'Curley Weaver', 'Blind Willie McTell & Curley Weaver', 'Blind Willie Mctell & The Regal Country Blues', 'Blind Willie McTell']},
"13215":{"count": 83, "artists":['Ma Rainey', 'Ma Rainey & Her Tub Jug Washboard Band']},
"13237":{"count": 7, "artists":['Peg Leg Howell']},
"13297":{"count": 46, "artists":['Barbecue Bob', 'Barbeque Bob']},
"13303":{"count": 70, "artists":['Georgia White']},
"13319":{"count": 151, "artists":['Cher', 'Theodis Ealey', 'Chuck Leavell', 'Kokomo Arnold', 'Eddie Kirkland', 'Celtas Cortos', 'Chick Willis']},
"17031":{"count": 589, "artists":['Otis Taylor', 'La Vern Baker', 'LaVern Baker', 'The Electric Flag', 'Electric Flag', 'Albert Ammons', 'Pete Johnson and Albert Ammons', 'Albert Ammons;Pete Johnson', 'Iscintilla', 'The Paul Butterfield Blues Band', 'Paul Butterfield', 'Marla Glen', 'Billy Boy Arnold', 'Little Walter', "Lurrie Bell - Billy Branch (Chicago's Young Blues Generation)", 'Lurrie Bell', 'Siegel-Schwall', 'Deitra Farr', 'Dave Specter', 'Specter', 'Big Bill Morganfield', 'Big Bill Morganfield & Taj Mahal', 'Gary Primich', 'Maurice John Vaughn', 'Das Waldemar Wunderbar Syndikat', 'Meade Lux Lewis', "Meade 'Lux' Lewis", 'Richie Arndt', 'Meade "Lux" Lewis', 'Jimmie Lee Robinson', 'Lou Pride']},
"17097":{"count": 20, "artists":['Billy Branch']},
"17119":{"count": 76, "artists":['Bonnie Raitt', 'Delaney & Bonnie And Friends', 'Delaney Bonnie & Friends', 'Delaney & Bonnie & Friends feat. King Curtis', 'Delaney & Bonnie & Friends']},
"17167":{"count": 400, "artists":['Nick Moss & The Flip Tops', 'Nick Moss_ The Flip Tops', 'Jimmy Johnson', 'Honeyboy Edwards', 'Joanna Connor', 'The Jelly Roll Kings', 'Jelly Roll Kings', 'The Great Crusades', 'Willie Big Eyes Smith', 'Little Arthur Duncan', 'Homesick James', 'Freddie Roulette', 'Lovie Lee', 'Lester Davenport', 'Little Willie Anderson', 'Studebaker John & The Hawks']},
"18063":{"count": 33, "artists":['Blue News', 'Left Lane Cruiser']},
"18089":{"count": 25, "artists":['Mighty Mo Rodgers']},
"18163":{"count": 20, "artists":['The Beat Daddys']},
"18167":{"count": 1, "artists":['Curtis Gordon']},
"19169":{"count": 19, "artists":['Radio Moscow']},
"20125":{"count": 75, "artists":['Tone Trump', 'Derek Trucks;Solomon Burke', 'Joe Henry', 'Burning Tree', 'Jeff Ray', 'West_ Bruce & Laing']},
"20173":{"count": 1, "artists":['The James Gang']},
"21047":{"count": 16, "artists":['Jhon Brim', 'John Brim', 'Todd Rhodes and his Orchestra']},
"21111":{"count": 86, "artists":["The Helen Humes_ Buck Clayton's Orchestra", 'Marshall Royal & His Orchestra_ Helen Humes', 'Helen Humes', 'Artimus Pyle (Lynyrd Skynyrd Alumni)', 'Sylvester Weaver;Walter Beasley', 'Sylvester Weaver', 'Edith Wilson', 'Edith Wilson  ', 'Edith Wilson & Lena Wilson']},
"21193":{"count": 49, "artists":['Roscoe Holcomb & The Stanley Brothers', 'Roscoe Holcomb']},
"22009":{"count": 82, "artists":['Little Walter & His Jukes', 'Little Walter / Otis Rush', 'Little Walter & His Night Cats', 'Little Walter_ Otis Rush', 'Little Walter']},
"22017":{"count": 49, "artists":['Mighty Joe Young', 'Tha Liks featuring Busta Rhymes']},
"22019":{"count": 83, "artists":['Clarence Gatemouth Brown', 'Clarence "Gatemouth" Brown', "Clarence 'Gatemouth' Brown", 'Clarence Brown', 'Gatemouth Brown', 'The Occasionals']},
"22027":{"count": 119, "artists":['Bobby Rush', 'Johnny Copeland']},
"22031":{"count": 12, "artists":["Ramblin' Thomas", "Ramblin' Thomas & The Dallas Blues Singers"]},
"22033":{"count": 115, "artists":['The Roots', 'Chris Thomas', 'Chris Thomas King', 'Tab Benoit', 'Robert Pete Williams & Robert \x1cGuitar" J. Welch', 'Robert Pete Williams']},
"22049":{"count": 52, "artists":['Jimmy Davis', 'Jimmie Davis']},
"22053":{"count": 13, "artists":['Phillip Walker']},
"22071":{"count": 483, "artists":['Louis Prima with Chorus', 'Louis Prima;Keely Smith', 'Louis Prima with Orchestra', 'The Memphis Minnie', 'Memphis Minnie', 'Lonnie Johnson', 'James Booker', 'Kenny Neal', 'Larry Garner', 'Sam Butera & The Witnesses', 'Earl King', 'Papa Charlie Jackson', 'Tommy Ridgely And His Band', 'Louis Prima', 'Tommy Ridgley', 'Linda Hopkins;Joyce Brown', 'Paul Gayten', 'Linda Hopkins']},
"22073":{"count": 82, "artists":['Mighty Sam McClain', 'Speckled Red']},
"22077":{"count": 7, "artists":['Lazy Lester']},
"22095":{"count": 2, "artists":['Sammy Price', 'Cousin Joe']},
"22097":{"count": 25, "artists":['Lonnie Brooks']},
"22099":{"count": 9, "artists":['Sherman Robertson']},
"22105":{"count": 186, "artists":['Irma Thomas / Tom McDermott', 'Irma Thomas / Norah Jones', 'Irma Thomas / Ellis Marsalis', 'Irma Thomas', 'Irma Thomas / Henry Butler', 'Irma Thomas / Davell Crawford', 'Irma Thomas / Dr. John', 'Irma Thomas / Marcia Ball', 'Irma Thomas / David Torkanowski', 'Ann Turner', 'Little Brother Montgomery']},
"22109":{"count": 77, "artists":['deadboy & the Elephantmen', 'Dax Riggs']},
"22117":{"count": 94, "artists":['Professor Longhair And His Blues Scholars', 'Professor Longhair And His New Orleans Boys', 'Roy Byrd & His Blues Jumpers', 'Professor Long Hair', 'Professor Longhair']},
"22119":{"count": 91, "artists":['Percy Mayfield']},
"22121":{"count": 53, "artists":['Dakota Station', 'Slim Harpo']},
"22125":{"count": 80, "artists":['Sam Collins', 'Little Freddie King', 'Long John Hunter', 'Dale And Grace', 'Dale & Grace', 'Spencer Bohren']},
"24005":{"count": 15, "artists":['Cheryl Wheeler']},
"24041":{"count": 8, "artists":['The Bakerton Group']},
"25025":{"count": 237, "artists":['The J. Geils Band', 'J. Geils Band', 'Bob Margolin', 'Cheater Slicks', 'Monster Mike Welch', 'Thaddeus Hogarth', 'Jon Butcher Axis']},
"25027":{"count": 48, "artists":['Albert Cummings', 'Georgia Gibbs', 'Chicago Bob Nelson']},
"26073":{"count": 25, "artists":['The Atomic Fireballs', 'Howling Diablos', 'Sir Mack Rice', 'Alberta Adams']},
"26121":{"count": 40, "artists":['Bettye Lavette']},
"26163":{"count": 229, "artists":['The White Stripes', 'The Raconteurs', 'Frijid Pink', 'Bob Hope_ Margaret Whiting', 'Deanna Bogart', 'Deanna Bogart Band', 'Cub Koda', 'Marvin Pontiac', 'Hank Ballard', 'Hank Ballard and the Midnighters', 'Midnighters', 'Kim Wilson', 'Tre Little', '8th Day', 'The 8th Day']},
"27001":{"count": 24, "artists":['Drones', 'The Blue Jays']},
"27053":{"count": 2, "artists":['Junior Parker', 'The Black Eyed Snakes']},
"27109":{"count": 1, "artists":['Joe Sun']},
"28001":{"count": 3, "artists":['Hound Dog Taylor', 'Elmo Williams & Hezekiah Early']},
"28007":{"count": 96, "artists":["Big Walter Horton's Blues Harp Band", 'Charles Musselwhite', 'Charlie Musselwhite', 'Scott Dunbar']},
"28011":{"count": 211, "artists":['Big Bill Broonzy', 'Honey Boy Edwards', 'David "Honeyboy" Edwards', 'David "Honey Boy" Edwards', 'David "Honeyboy" Edwards / Floyd Jones / Kansas City Red / Sunnyland Slim / Big Walter Horton', 'Eddie C', 'Eddie C. Campbell', 'Eddie Taylor', 'Eddie Taylor_ Sunnyland Slim_ Carey Bell_ Hubert Sumlin_ Robert Stroger_ Odie Payne', 'Henry Townsend']},
"28017":{"count": 180, "artists":['Glen Campbell And Bobbie Gentry', 'Bobbie Gentry', 'Bukka White', 'Frank Ifield']},
"28025":{"count": 135, "artists":['Howlin Wolf', 'Howlin\x19 Wolf', 'Howling Wolf', 'Howlin  Wolf', "Howlin' Wolf", 'Zora Young']},
"28027":{"count": 328, "artists":['John Lee Hooker & Jimmie Vaughn', 'Muddy Waters', 'John Hooker', 'John Lee Hooker & Carlos Santana', 'John Lee Hooker_ Booker T_ Randy California', "Lightnin' Hopkins", 'John Lee Hooker', 'Albert King', 'The Soul Stirrers', 'Earl Hooker', 'Little Jr. Parker', 'Ike & Tina Turner', 'Ike_ Tina Turner', 'Eddie Boyd_ Buddy Guy_ Lonesome Jimmy Lee_ Freddie Below', 'Eddie Boyd', 'Little Junior Parker', 'Johnny B. Moore', 'Little Junior', 'Jimmy Burns', 'Junior Parker']},
"28029":{"count": 105, "artists":['Robert Johnson', 'Robert Lockwood Jr', 'David "Honeyboy" Edwards', 'Bukka White', 'Robert Johnson / Philip Kraus / Chicago Symphony Chorus / Chicago Symphony Orchestra / Sir Georg Solti', 'Pedro Pardo']},
"28033":{"count": 120, "artists":['North Mississippi All Stars', 'North Mississippi Allstars', 'The North Mississippi Allstars', 'Walter Horton', 'Robert Wilkins']},
"28043":{"count": 59, "artists":['Magic Sam']},
"28049":{"count": 377, "artists":["Howlin' Wolf", 'Willie Brown', 'David "Honeyboy" Edwards', 'Robert Johnson', 'Charly Patton', 'Blind Willie Johnson', 'Charley Jordan', 'Charlie Patton', 'Son House', 'Tommy Johnson', 'Otis Spann', 'Otis Spann;Fleetwood Mac', 'The Mississippi Sheiks', 'Mississippi Sheiks & Chatman Brothers', 'Los Hermanos Rincon', 'Charley Patton', 'Little Johnny Jones', 'Othar Turner', 'Othar Turner and the Rising Star Fife and Drum Band', 'Mississippi Sheiks', 'Ishman Bracey', 'McKinley Mitchell', 'Bo Carter', 'Carl Weathersby', 'Ishmon Bracey', 'Leadbelly & Friends']},
"28051":{"count": 54, "artists":['Evgeny Mravinsky', 'Jimmy Dawkins', 'Lonnie Pitchford']},
"28071":{"count": 92, "artists":['R.L. Burnside']},
"28073":{"count": 21, "artists":['Johnny Rawls']},
"28077":{"count": 153, "artists":['J. B. Lenoir', 'J.B Lenoir', 'JB Lenoir', 'J.B.Lenoir', 'Byther Smith', 'J.B. Lenoir']},
"28083":{"count": 135, "artists":['Hubert Sumlin', 'Denise La Salle', 'Pee Wee Crayton', 'Fenton Robinson', 'Denise Lasalle']},
"28087":{"count": 82, "artists":['Big Joe Williams', "Lightnin' Hopkins"]},
"28089":{"count": 120, "artists":['Eden Brent', 'Cleo Brown', 'Joe Turner_ Joe Houston_ L. C. Williams', 'Joe Turner & Pluma Davis Orchestra', 'Joe Turner;T-Bone Walker;Otis Spann', 'Joe Turner / Count Basie & His Orchestra', 'Joe Turner / Pee Wee Crayton / Sonny Stitt', 'Big Joe Turner', 'Joe Turner']},
"28095":{"count": 31, "artists":['Lucille Bogan']},
"28099":{"count": 67, "artists":['Otis Rush']},
"28103":{"count": 94, "artists":['Carey Bell; Anthony Striplen', 'Carey Bell_ Lazy Lester_ Raful Neal & Snooky Pryor', 'Eddy Clearwater', 'Eddy  Clearwater', 'Carey Bell']},
"28107":{"count": 88, "artists":['Lavredis Maheritsas', 'Mississippi Fred Mc Dowell', 'Throw That Beat In The Garbagecan!', 'Big Daddy Kinsey', 'Mississippi Fred McDowell']},
"28119":{"count": 56, "artists":['Super Chikan', 'Pequena Compania (F)', 'Big Jack Johnson']},
"28121":{"count": 92, "artists":['Elmore James']},
"28123":{"count": 128, "artists":['Arthur Big Boy Crudup', "Arthur 'Big Boy' Crudup", 'Arthur Crudup', 'Arthur \x18Big Boy\x19 Crudup', 'Arthur "Big Boy" Crudup', 'Arthur " Big Boy"crudup', 'Big Boy Crudup', 'John Littlejohn']},
"28125":{"count": 138, "artists":['Muddy Waters;Johnny Winter;James Cotton', 'Sunnyland Slim', 'Buddy Guy / Muddy Waters', 'Muddy Waters / Son Simms Four', 'Sonny Boy Williamson', 'Muddy Waters', 'Muddy Waters & His Guitar', 'Johnny Dyer']},
"28133":{"count": 375, "artists":['Albert King', 'Albert King / Stevie Ray Vaughan', 'Little Milton', 'Jimmy Rogers & His Rocking Four', 'Jimmy Rogers', 'Jimmie Rodgers', 'Jimmy Rodgers', 'Willie Kent', 'Bill "Jazz" Gillum', 'Bill Jazz Gillum', 'Jazz Gillum']},
"28135":{"count": 88, "artists":['John Lee Williamson', "John Lee 'Sonny Boy' Williamson", 'Sonny Boy Willamson', 'Sonny Boy Williamson']},
"28137":{"count": 28, "artists":['Jessie Mae Hemphill', 'Jesse Mae Hemphill', 'Big Time Sarah']},
"28143":{"count": 98, "artists":['James Cotton', 'The James Cotton Band', 'Doctor Ross']},
"28149":{"count": 141, "artists":["Howlin' Wolf", 'Willie Dixon / Memphis Slim', 'Willie Mabon', 'Koko Taylor', 'Willie Dixon and Memphis Slim', 'Willie Dixon & The All Stars', 'Willie Dixon', 'Little Walter', 'Willie Dixon / The Big Three Trio', 'Louisiana Red', 'Artie "Blues Boy" White', 'Lousiana Red']},
"28151":{"count": 89, "artists":['Jimmy Reed', 'Sasa Crnobrnja']},
"28163":{"count": 209, "artists":['Skip James', 'Leadbelly & Friends', 'Tommy McClennan & Robert Petway', 'Tommy McClennan', 'Big Joe Turner', 'Big Joe Williams', 'James "Son" Thomas & Cleveland "Broomman" Jones', 'James "Son" Thomas']},
"29021":{"count": 160, "artists":['Coleman Hawkins-Ben Webster', 'Coleman Hawkins_ Kenny Clarke', 'Coleman Hawkins / Pee Wee Russell', 'Coleman Hawkins - Roy Eldridge Quintet', 'Coleman Hawkins / Red Garland Trio', 'Fats Waller', 'Django Reinhardt - Benny Carter - Hawkins C. All Star Jam Band', 'Coleman Hawkins']},
"29095":{"count": 62, "artists":['Big Joe Turner feat. Piano Man  Walls', 'Joe Turner', 'Big Joe Turner', 'Larry davis']},
"29131":{"count": 16, "artists":['Grand Marquis', 'Grand Marquis & Inacio', 'Grand Marquis & Wiser']},
"29155":{"count": 15, "artists":['A.C. Reed', 'Stevie Ray Vaughan;A.C. Reed']},
"29510":{"count": 113, "artists":['Bill Doggett', "Lightnin' Slim", 'Lightning Slim', 'Jimmy McCracklin']},
"30093":{"count": 35, "artists":['Ustad Vilayat Khan', 'Martha Raye', 'Martha Raye_ Jimmy Dorsey Orchestra', 'Arthur Montana Taylor', 'Montana Taylor']},
"30107":{"count": 12, "artists":['Philip Aaberg;Scott Mathews', 'Philip Aaberg', 'Philip Aaberg;Barbara Higbie;Daniel Kobialka', 'Philip Aaberg;Darol Anger']},
"31055":{"count": 108, "artists":['Buddy Miles', 'Harris_ Wynonie', 'T Bone Walker', "Wynonie Harris feat. Lucky Millinder's Orchestra", 'Bob Moseley', 'Curtis Salgado', 'Wynonie Harris', "Sam 'The Man' Taylor"]},
"33011":{"count": 3, "artists":['Bassekou Kouyate & Ngoni Ba', 'Bassekou Kouyate_ Ngoni ba', 'Bassekou Kouyate & Ngoni Ba featuring Harouna Samake']},
"34005":{"count": 6, "artists":['Lonnie Youngblood']},
"34009":{"count": 98, "artists":['Freebo', 'Mick Chillage', 'Walter Trout']},
"34013":{"count": 39, "artists":['Faye Adams']},
"34017":{"count": 1, "artists":['Deanie Parker & The Valadors']},
"35057":{"count": 25, "artists":['Magic Slim', 'Magic Slim & The Teardrops']},
"36005":{"count": 58, "artists":['Popa Chubby']},
"36029":{"count": 32, "artists":['Lucky Peterson']},
"36047":{"count": 199, "artists":['Richie Havens', 'Lee Fields & The Expressions', 'Al Kooper;Steve Stills', 'Al Kooper;Mike Bloomfield;Stephen Stills', 'Shuggie Otis', 'Al Kooper', 'Al Kooper;Shuggie Otis', 'TK Webb_ The Visions', 'Garland Jeffreys', 'Garland Jeffreys / Joe Dworniak', 'Al Kooper;Mike Bloomfield', 'Bex Marshall', 'Paul Oscher', 'Stefan Grossman and Tokio Uchida', 'Stefan Grossman']},
"36061":{"count": 627, "artists":['Pete Seeger_ Sonny Terry and Brownie McGhee', 'Davis Coen', 'Deville_ Willy', 'Willy De Ville', 'Eric Bibb', 'Andre Mehmari', 'Michal', 'Mike Farris', 'Mike Farris featuring The McCrary Sisters', 'The Waves', 'Mink DeVille', 'Leslie West', 'David Gilmour', 'London Symphony Orchestra and Leopold Ludwig', 'Rory Block', 'Guy Davis_ Tyrick Wiltez Jones', 'Guy Davis', 'Shemekia Copeland', 'Al Duvall', 'Al Duvall And Singing Sadie', 'Tad Robinson', 'Ann Rabson', 'The Blues Project', 'Pinetop Perkins', 'Ronnie Earl', 'Doug MacLeod_ Doug MacLeod', 'Doug MacLeod', 'Chrome Cranks', 'The Chrome Cranks', 'The John Earl Walker Band', 'Willy DeVille', 'Marc Hirte', 'Roy Bookbinder', 'Doc Pomus', 'Foghat', 'Barbara Lea', 'Big Joe Turner']},
"36071":{"count": 54, "artists":['Bill Perry & Richie Havens', 'Bill Perry']},
"37007":{"count": 79, "artists":['Blind Boy Fuller']},
"37013":{"count": 17, "artists":['Guitar Shorty']},
"37027":{"count": 6, "artists":['Etta Baker']},
"37063":{"count": 77, "artists":['Betty Davis', 'John D. Loudermilk']},
"37081":{"count": 198, "artists":['Absynthe Minded', 'Sonny Terry & Brownie McGhee With The Chris Barber Band & Ottilie Patterson', 'Sonny Terry & Brownie McGhee With The Chris Barber Band', 'Sonny Terry', 'Blind Boy Fuller_ Sonny Terry', 'Sonny Terry & Brownie McGhee', 'Sonny Terry / Brownie McGhee', 'Sonny Terry & Alan Gilbert', 'Sonny Terry_ J.C. Burris_ and Sticks McGhee', 'Josh White']},
"37115":{"count": 10, "artists":['Bascom Lamar Lunsford', 'Mississippi John Hurt']},
"37119":{"count": 29, "artists":['Nappy Brown']},
"37123":{"count": 49, "artists":['Precious Bryant', 'Bill Phillips', 'Slick Ballinger']},
"37183":{"count": 29, "artists":['Steve Cropper & Felix Cavaliere', 'Steve Cropper / Pop Staples / Albert King', 'Steve Cropper']},
"37195":{"count": 3, "artists":['Tarheel Slim']},
"38017":{"count": 12, "artists":['Shannon Curfman', 'Shannon Curfman & Joe Bonamassa']},
"39027":{"count": 1, "artists":['Gran Bel Fisher']},
"39035":{"count": 127, "artists":['David Coverdale', 'James Gang', 'Joachim Pfahl', 'Freddie Brocksieper', 'The James Gang', 'John Popper', 'Bullmoose Jackson', 'Ernie Freeman Combo', 'Bull Moose Jackson', 'Carr_ Wynona', 'Sister Wynona Carr / C.L. Franklin / New Bethel Baptist Church Choir', 'Sister Wynona Carr', 'Wynona Carr']},
"39049":{"count": 49, "artists":['Bassholes', 'The Gibson Bros.']},
"39061":{"count": 43, "artists":['Over The Rhine']},
"39093":{"count": 57, "artists":['Los Enemigos']},
"39095":{"count": 97, "artists":['Art Tatum']},
"39099":{"count": 14, "artists":['Tiny Bradshaw']},
"39107":{"count": 62, "artists":['Rick Derringer']},
"39113":{"count": 49, "artists":['Margo Smith', 'Margo Smith & Holly']},
"39153":{"count": 89, "artists":['The Black Keys']},
"40015":{"count": 25, "artists":['Jesse Ed Davis', 'Jesse Davis']},
"40031":{"count": 86, "artists":['Leon Russell & New Grass Revival', 'Leon Russell', 'Leon Russel']},
"40049":{"count": 46, "artists":['Roy Milton & His Solid Serenades', 'Milton_ Roy', 'Roy Milton']},
"40083":{"count": 43, "artists":['Joe Liggins and his Honeydrippers_ Blue Flamingo', 'Joe Liggins & His Honeydippers', 'Joe Liggins / The Honeydrippers', 'Joe Liggins & His Honeydrippers', 'Joe Liggins']},
"40101":{"count": 55, "artists":['Walter Brown', 'Jay McShann and His Orchestra', 'Jay McShann and His Orchestra & Charlie Parker', 'Jay McShann', 'Brown McGhee_ Jay McShann & Eddie "Cleanhead" Vinson', 'Jay McShann &  His Sextette_ Jimmy Witherspoon']},
"40109":{"count": 118, "artists":['J. J. Cale & Eric Clapton', 'J.J. Cale & Eric Clapton', 'J.J. Cale', 'Jimmy Rushing']},
"40115":{"count": 39, "artists":['Ace Moreland']},
"40143":{"count": 95, "artists":['Lowell Fulson']},
"41013":{"count": 50, "artists":['Mary Flower']},
"41051":{"count": 34, "artists":['Hillstomp']},
"42003":{"count": 22, "artists":['Jimmy Thackery', 'Jimmy Thackery And The Drivers', 'T.Rex', 'John Davidson']},
"42007":{"count": 2, "artists":['Papa John Creach']},
"42027":{"count": 104, "artists":['Pumice', 'Gina Sicilia', 'Steve Guyger', 'The Paramounts', 'John Long', 'Billy Price_ Fred Chapellier']},
"42055":{"count": 29, "artists":['Ed McCurdy']},
"42077":{"count": 1, "artists":['John Mayall']},
"42101":{"count": 176, "artists":['G. Love & Special Sauce', 'Son House', 'Jimmy Nelson', 'Jimmy Nelson & Peter Rabbit Trio', 'Jimmy Nelson and the Peter Rabbit Trio']},
"42129":{"count": 41, "artists":['Norma Jean']},
"44003":{"count": 7, "artists":['Les Dudek']},
"44007":{"count": 85, "artists":['Duke Robillard', 'The Lively Ones', 'Geremia', 'Kent', 'Paul Geremia', 'Frederic de Roos', 'Roomful Of Blues']},
"45007":{"count": 1, "artists":['Kip Anderson']},
"45011":{"count": 16, "artists":['J.B. Hutto']},
"45019":{"count": 30, "artists":['H-Bomb Ferguson', 'H-Bomb Ferguson & Andy Kirk Orchestra', 'Charles Singleton', 'Willie "Big Eyes" Smith']},
"45031":{"count": 26, "artists":['Buddy Johnson', 'Ella & Buddy Johnson', 'Buddy Johnson & His Orchestra / Ella Johnson / The Bee Jays']},
"45033":{"count": 1, "artists":['Jimmy Hamilton']},
"45059":{"count": 133, "artists":['Rev. Blind Gary Davis', 'Sidonio Pereira', 'The New Lost City Ramblers', 'Blind Gary Davis', 'Reverend Gary Davis', 'Pink Anderson', 'Rev. Gary Davis']},
"45075":{"count": 120, "artists":['Davis Coen', 'Marvin Sease']},
"45087":{"count": 12, "artists":['Peg Leg Sam featuring Louisiana Red', 'Peg Leg Sam']},
"47011":{"count": 40, "artists":['Latimore']},
"47015":{"count": 306, "artists":['Turbo Fruits', 'Muriel Anderson', 'Toranja', 'Scott Holt', 'Mila Mason', 'Susan Marshall', 'Marshall_ Susan', 'Eric Hughes Band', 'Hour Glass Men', 'Kevin McKendree', 'David Evans;Michele Pawk;Carolee Carmello', 'David Evans;John Dossett;Judy Blazer;Carolee Carmello;Donna Murphy;Malcolm Gets;John Cameron Mitchell;Michael Park;Dennis Parlato;Michele Pawk;David A. White', 'David Evans;Malcolm Gets', 'David Evans;John Cameron Mitchell;Carolee Carmello;John Dossett;Michael Park;Dennis Parlato;David A. White', 'David Evans;Judy Blazer;Michael Park', 'David Evans;David A. White;Judy Blazer;John Dossett;Michael Park;Michele Pawk', 'David Evans;John Cameron Mitchell;Dennis Parlato;Michele Pawk', 'David Evans', 'David Evans;Carolee Carmello;David A. White;John Cameron Mitchell;Judy Blazer;Michele Pawk;Dennis Parlato;Malcolm Gets', 'David Evans;Malcolm Gets;John Cameron Mitchell', 'David Evans;Donna Murphy;David A. White', 'Joe Sample', 'Joe Stampley', 'Arthur Godfrey', 'Smokehouse', 'William Lee Ellis', 'Bobo Moreno', 'Big Al & The Heavyweights', 'Big Al_ The Heavyweights', 'Big Al & The Heavy Weights', 'Harlan T. Bobo', 'Joanna Cotten']},
"47037":{"count": 211, "artists":['Gregg Allman', 'Duane Allman', 'Johnny Jenkins / Duane Allman', 'Duane Allman / Derek & The Dominos', 'John Hammond / Duane Allman', 'Duane Allman / Delaney Bonnie & Friends', 'Leroy Carr', 'Ellen McIlwaine', 'Arthur Gunter', 'St Louis Jimmy Oden', 'St. Louis Jimmy Oden_ St. Louis Jimmy', 'St. Louis Jimmy Oden', 'Cecil Grant', 'Cecil Gant']},
"47065":{"count": 76, "artists":['Bessie Smith']},
"47075":{"count": 26, "artists":['Yank Rachell', 'Yank Rachel']},
"47093":{"count": 81, "artists":['Sonny Terry & Brownie McGhee', 'Brownie McGhee', 'Brownie Mc Ghee']},
"47097":{"count": 150, "artists":['Sleepy John Estes & John Henry Barbee', 'Sleepy John Estes', 'Peetie Wheatstraw']},
"47113":{"count": 70, "artists":['Claudio Scimone', 'Mario Hospach-Martini', 'Big Maybelle']},
"47133":{"count": 24, "artists":['Roy Roberts']},
"47143":{"count": 20, "artists":['Howard Armstrong']},
"47157":{"count": 591, "artists":['Koko Taylor_ Little Walter_ Hound Dog Taylor_ Dillard Crume_ Odie Payne', 'Koko Taylor', 'James Brown', 'Amy La Vere', 'Bobby "Blue" Bland / Little Junior Parker', 'Bobby "Blue" Bland & Junior Parker', 'Bobby Blue Bland', 'Tsin Ting', 'Bobby "Blue" Bland', 'Bobby Bland', 'William Bell', 'William Bell / Judy Clay', 'Memphis Slim / Buddy Guy', 'Memphis Slim', 'Ruth Brown', 'Memphis Slim / Willie Dixon', 'Memphis Slim / Roosevelt Sykes', 'Johnny Shines', 'Compulsive Gamblers', "Alberta Hunter / Lovie Austin's Blues Serenaders", 'Josephine Beatty', 'Alberta Hunter', 'Victoria Spivey', 'Big Mama Thornton / Johnny Ace / The Johnny Otis Band', 'Willie Mabon', 'Bluff City Backsliders', 'Woody Herman & His Orchestra', 'Frank Stokes', 'Banda Da Forca Publica Do Estado De SP', 'Joe Hill Louis', 'Booker T Laury', 'Junior Wells', 'The Willie Mabon Combo']},
"47163":{"count": 47, "artists":['Louise Johnson', 'Andrea Braido', 'Cripple Clarence Lofton']},
"48021":{"count": 1, "artists":['Theodis Ealey']},
"48029":{"count": 72, "artists":['Chris Duarte', 'Doug Sahm Tex Mex Trip', 'Sir Douglas Quintet', 'The Sir Douglas Band', 'Doug Sahm', 'Wayne Douglas', 'Doug Sahm and the Texas Mavericks']},
"48037":{"count": 3, "artists":['Little Hat Jones', 'Special EFX', 'Robert Ealey']},
"48067":{"count": 77, "artists":['Amos Milburn', "T-Bone Walker_ Marl Young's Orchestra", 'Dinah Washington', 'T-Bone Walker / Jazz At The Philharmonic', 'T Bone Walker', 'T-Bone Walker']},
"48095":{"count": 260, "artists":['Blind Lemon Jefferson', 'Jeremy Kay', 'Chris Watson', 'Andrew "Jr. Boy" Jones', 'Jim Suhler & Monkey Beat_ Jim Suhler_ Monkey Beat', 'Gurf Morlix', 'Doyle Bramhall II', 'Bramhall', 'Cold Blue Steel', 'Joe Lopez', 'Bessie Tucker', 'The Joe Richardson Express', 'Marc Benno', 'Galea', 'John Nitzinger', 'Ruthie Foster', 'Galea & Langford']},
"48113":{"count": 196, "artists":['Stevie Ray Vaughan & Double Trouble', 'Stevie Ray Vaughan And Double Trouble', 'Stevie Ray Vaughan;Double Trouble', 'Stevie Ray Vaughan', 'Jimmie Vaughan', 'Doyle Bramhall', 'Hot Lips Page', 'Hot Lips Page_ His Band', 'Lillian Glinn', 'Walter Brown', "Walter Brown_ Jay McShann'S Orchestra"]},
"48145":{"count": 96, "artists":['Blind Willie Johnson']},
"48185":{"count": 116, "artists":['Mance Lipscomb']},
"48201":{"count": 204, "artists":['Chris Whitley', 'Ndidi Onukwulu', 'Katie Webster', 'Sippie Wallace_ Little Brother Montgomery_ Jack Myers_ Freddie Below', 'Sippie Wallace', 'Eddie "Cleanhead" Vinson & The Young Blues Thrillers', "Eddie 'Cleanhead' Vinson", 'Eddie Cleanhead Vinson', 'Eddie Vinson', 'Eddie "Cleanhead" Vinson', 'Trudy Lynn', 'Joe "Guitar" Hughes']},
"48203":{"count": 47, "artists":['Floyd Dixon / Willie Dixon', 'Floyd Dixon', 'Whirl Magnet']},
"48241":{"count": 74, "artists":['Ivory Joe Hunter', 'Ivory Joe Hunter & His Band']},
"48245":{"count": 96, "artists":['Edgar Winter;Johnny Winter', 'Edgar Winter_ Bill Bruford_ Tony Levin', 'Edgar Winter;The Edgar Winter Group', 'Edgar Winter', 'Edgar Winter & Rick Derringer', 'Johnny Winter', 'Barbara Lynn']},
"48289":{"count": 36, "artists":['Albert Collins / B.B. King / Albert Collins', 'Albert Collins']},
"48303":{"count": 61, "artists":['Delbert McClinton', 'Don Covay & Angela Strehli', 'Angela Strehli']},
"48309":{"count": 13, "artists":['Billy Williams']},
"48331":{"count": 80, "artists":['Pee Wee Crayton & His Guitar', 'Pee Wee Crayton']},
"48343":{"count": 96, "artists":['Z.Z. Hill', 'Z Z Hill', 'ZZ Hill', 'Z. Z. Hill', 'Z.Z.HILL']},
"48361":{"count": 9, "artists":['Marcia Ball With Band', 'Marcia Ball', 'Daryle Singletary']},
"48439":{"count": 43, "artists":['Mason Ruffner', 'Ella Mae Morse']},
"48453":{"count": 176, "artists":['Scott H. Biram', 'The Fabulous Thunderbirds', 'Guy Forsyth', 'Omar & The Howlers', 'Marieke', 'Alan Lomax', 'Lou Ann Barton']},
"48477":{"count": 82, "artists":['Darden Smith', 'Concordia Chamber Ensemble']},
"50017":{"count": 26, "artists":['Scott Ainslie']},
"51013":{"count": 12, "artists":['Ramsay Midwood']},
"51017":{"count": 23, "artists":['Chris Evans', 'Paul Curreri']},
"51033":{"count": 23, "artists":['Cephas & Wiggins', 'Omar', 'John Cephas & Phil Wiggins']},
"51063":{"count": 22, "artists":['Blind Alfred Reed']},
"51067":{"count": 31, "artists":['Archie Edwards']},
"51157":{"count": 54, "artists":['John Jackson']},
"51195":{"count": 2, "artists":['Paulette Reaves', 'Carl Martin']},
"51630":{"count": 18, "artists":['Gaye Adegbalola']},
"51710":{"count": 46, "artists":['Keely Smith', 'Keely Smith / Frankie Capp Orchestra']},
"51720":{"count": 49, "artists":['Old Man Tha Husla', 'Dock Boggs']},
"51740":{"count": 151, "artists":['Ruth Brown', 'Swamp Dogg', 'Deborah Coleman']},
"53033":{"count": 10, "artists":['Stone Gossard']},
"53053":{"count": 47, "artists":['Zoot Sims - Bob Brookmeyer', 'Kelly Jo Phelps', 'Cacique and Paje', 'Kelly Joe Phelps']},
"53063":{"count": 61, "artists":["Danny O'Keefe"]},
"54045":{"count": 29, "artists":['Frank Hutchinson', 'Frank Hutchison']},
"55073":{"count": 16, "artists":['Jeffrey Foucault', 'Cash Box Kings']},
"55079":{"count": 44, "artists":['Steve Miller / Lol Coxhill', 'Steve Miller', 'Peter Mulvey']},
};
