var country = {
"01001":{"count": 3, "artists":['Travis Wammack']},
"01013":{"count": 1, "artists":['Marty Raybon']},
"01017":{"count": 41, "artists":['Razzy Bailey']},
"01029":{"count": 4, "artists":['Johnny Darrell']},
"01033":{"count": 36, "artists":['Mo', 'Shenandoah']},
"01073":{"count": 94, "artists":['Ray Charles;Hank Williams_ Jr.', 'Emmylou Harris with Gram Parsons', 'Celine Frisch', 'Emmylou Harris with Dolly Parton and Linda Ronstadt', 'Emmylou Harris with Ricky Skaggs', 'Earl Thomas Conley;Emmylou Harris', 'Emmylou Harris', 'Emmylou Harris / Alison Krauss / Gillian Welch', 'Mary Black Feat. Emmylou Harris & Dolores Keane']},
"01081":{"count": 16, "artists":['Adam Hood']},
"01093":{"count": 41, "artists":['Sonny James']},
"01115":{"count": 28, "artists":['Jeanne Pruett']},
"01119":{"count": 23, "artists":['Jaybird Coleman & Birmingham Jug Band', 'Jaybird Coleman']},
"02170":{"count": 47, "artists":['Barbara Fairchild']},
"04013":{"count": 140, "artists":['Marty Robbins', 'Jessi Colter']},
"04019":{"count": 118, "artists":['Linda Ronstadt & Emmylou Harris', 'Linda Ronstadt featuring Aaron Neville', 'Linda Ronstadt with James Taylor', 'James Ingram;Linda Ronstadt', 'Green On Red', 'Linda Ronstadt']},
"05003":{"count": 40, "artists":['K.T. Oslin', 'K T Oslin']},
"05061":{"count": 67, "artists":['Jimmy Wakely']},
"05093":{"count": 31, "artists":['Edwin Bruce', 'Ed Bruce']},
"05109":{"count": 83, "artists":['Gladys Knight', 'Glen Campbell', 'Turisas']},
"05119":{"count": 79, "artists":['Dan Hicks & His Hot Licks', 'Dan Hicks and The Accoustic Warriors', 'Dan Hicks', 'Joy Lynn White', 'Charlie Jordan', 'Charley Jordon', 'Charley Jordan']},
"05133":{"count": 91, "artists":['Collin Raye;Joe Diffie', 'Collin Raye']},
"06019":{"count": 112, "artists":['Loggins And Messina', 'Loggins & Messina', 'The Nucleus', 'Rancho Deluxe', "Let's Get Out of This Terrible Sandwich Shop", 'Lets Get Out Of This Terrible Sandwich Shop', 'Sweethearts of the Rodeo;David Allan Coe', 'Ron Elliott', 'Chris Gaffney and the Cold Hard Facts']},
"06037":{"count": 601, "artists":['Flying Burrito Brothers', 'Zarama', 'The Flying Burrito Brothers', 'Johnny Horton', 'Eastmountainsouth', 'Bargain Music', 'Poco', 'KEVIN WELCH', 'Kevin Welch & Henning Kvitnes', 'Karla Bonoff', 'Brewer & Shipley', 'Blood On The Saddle', 'Ill Lit', 'Los Hermanos Dalton', 'Randy Weeks', 'The Geraldine Fibbers', 'Chris Hillman', 'Chris Hillman & Herb Pederson', 'The Boxmasters feat. Billy Bob Thornton', 'El Pino & the Volunteers', 'Taylor Swift', 'Southern Pacific', 'Gene Parsons', 'Speedbuggy USA', 'Kurt Tepperwein', 'Highway 101']},
"06043":{"count": 38, "artists":['Roy Rogers', 'Sons Of The Pioneers;Roy Rogers', 'Sons Of The Pioneers']},
"06059":{"count": 92, "artists":['Sammi Smith', 'Chris Wall']},
"06073":{"count": 98, "artists":['Ann Wilson / Elton John', 'Ann Wilson;Nancy Wilson', 'Ann Wilson / k.d. lang', 'Ann Wilson', 'Ann Wilson / Nancy Wilson / Deana Carter / Wynonna', 'Ann Wilson / Gretchen Wilson', 'Ann Wilson / Rufus Wainwright / Shawn Colvin', 'Ann Wilson / Nancy Wilson', 'Ann Wilson / Alison Krauss', 'Ann Wilson / Wynonna', 'Pacific Ocean Fire', 'Pacific Ocean Fire_ Naim Corteze', 'The Beat Farmers', 'Granfaloon Bus']},
"06075":{"count": 224, "artists":['Moby Grape', 'Jerry Garcia;Mickey Hart', 'Merl Saunders / Jerry Garcia / John Kahn / Bill Vitt', 'Merl Saunders / Jerry Garcia', 'Jerry Garcia;David Grisman;john kahn', 'Jerry Garcia / Merl Saunders / John Kahn / Bill Vitt', 'The Beau Brummels', 'Beau Brummels', 'Tarnation', 'Paul Kantner;Grace Slick', 'Paul Kantner', 'Jolie Holland', 'Bob Weir', 'Steel Rain']},
"06079":{"count": 54, "artists":['Brenda Holloway']},
"06087":{"count": 60, "artists":['Camper Van Beethoven']},
"06113":{"count": 53, "artists":['Thin White Rope', 'Middle Of The Road']},
"08013":{"count": 105, "artists":['Jello Biafra_ Randy Bachman_ Chris Houston_ and Garnet Sweatshirt', 'DJ Nukem & Marrocco', 'Jello Biafra with The Melvins', 'Firefall', 'Jello Biafra']},
"08031":{"count": 67, "artists":['Corey Harris', 'Ghost Buffalo']},
"08069":{"count": 35, "artists":['Drag The River']},
"08093":{"count": 1, "artists":['Fred Eaglesmith']},
"09009":{"count": 53, "artists":['The Child Molesters', 'The Mustangs']},
"10003":{"count": 50, "artists":['Cisco Houston']},
"11001":{"count": 61, "artists":['Rachel Harrington', 'Duck Baker', 'Go To Blazes']},
"12031":{"count": 102, "artists":['Blind Blake & The Royal Victoria Hotel Calypsos', 'Blind Blake', 'Jelly Roll Morton_ Johnny Dodds_ Blind Blake_ Jimmy Bertrand']},
"12039":{"count": 70, "artists":['Billy Dean']},
"12057":{"count": 78, "artists":['Pam Tillis']},
"12083":{"count": 73, "artists":['Jerry Reed']},
"12105":{"count": 68, "artists":['The International Submarine Band', 'Gram Parsons / Emmylou Harris', 'The Flying Burrito Brothers', 'Gram Parsons']},
"13021":{"count": 31, "artists":['Robert Petz und seine Weinbeier', 'Jason Aldean']},
"13059":{"count": 56, "artists":['Patterson Hood', 'Summer Hymns']},
"13063":{"count": 81, "artists":['Jesse Fuller']},
"13077":{"count": 73, "artists":['Doug Stone', 'Steve Young']},
"13081":{"count": 61, "artists":['T Graham Brown', 'T. Graham Brown']},
"13121":{"count": 183, "artists":['Confederate Railroad', 'Kelly Hogan', 'The Rockingbirds feat. Lesley Rankine', 'The Rockingbirds', 'Faron Young', 'Roy Drusky with Sylvie', 'Roy Drusky', 'Sugarland']},
"13127":{"count": 58, "artists":['Bumble Bee Slim']},
"13185":{"count": 61, "artists":['Billie Joe Royal', 'Billy Joe Royal', 'Les Humphries Singers']},
"13189":{"count": 88, "artists":['Blind Willie', 'Ruth Willis', 'Blind Willie & Partner', 'Blind Willie McTell_ Ruth Willis', 'Blind Samie', 'Curley Weaver', 'Blind Willie McTell & Curley Weaver', 'Blind Willie Mctell & The Regal Country Blues', 'Blind Willie McTell']},
"13237":{"count": 7, "artists":['Peg Leg Howell']},
"13295":{"count": 48, "artists":['The Forester Sisters']},
"13297":{"count": 45, "artists":['Barbecue Bob', 'Barbeque Bob']},
"13319":{"count": 74, "artists":['The Lost Trailers', 'Charlie Robinson', 'Kokomo Arnold']},
"17005":{"count": 39, "artists":['Gretchen Wilson']},
"17031":{"count": 311, "artists":['Jimmy Wakely', 'Otis Taylor', 'Jack Nitzsche', 'Jack Nitzche', 'Alena', 'The Waco Brothers', 'The Handsome Family', 'Pinetop Seven', 'Mason Proffit', 'An Albatross', 'Roger McGuinn', 'Alice Peacock']},
"17051":{"count": 2, "artists":['Tex Williams & Tex Ritter']},
"17055":{"count": 2, "artists":['Billy Grammer']},
"17097":{"count": 5, "artists":['The International Submarine Band']},
"17131":{"count": 52, "artists":['Suzy Bogguss']},
"17167":{"count": 28, "artists":['Robbie Fulks']},
"18039":{"count": 54, "artists":['Roberto Jordan', 'Connie Smith']},
"19169":{"count": 2, "artists":['Pieta Brown', 'Tiao Carreiro and Pardinho']},
"20045":{"count": 5, "artists":['The Belles']},
"20125":{"count": 152, "artists":['Joe Henry', 'Crosby / Nash', 'Bonnie Somerville', 'The Great Divide', "The Shakin' Apostles", 'Manassas', 'Jim Ford', 'Silvertone', 'Crosby & Nash', 'Rex Allen_ Jr.', 'REX ALLEN JR.']},
"20173":{"count": 25, "artists":['Justin Rutledge', 'Marvin Rainwater']},
"21021":{"count": 112, "artists":['Montgomery Gentry', 'John Michael Montgomery', 'John Michael Montgomery (Featuring Sixwire)']},
"21029":{"count": 1, "artists":['John Paul Jones']},
"21063":{"count": 45, "artists":['Keith Whitley', 'Keith Whitley;Earl Thomas Conley']},
"21081":{"count": 77, "artists":['Skeeter Davis']},
"21095":{"count": 5, "artists":['Rusty York']},
"21111":{"count": 26, "artists":['PLIHAL KAREL', 'Sundowners', 'Sylvester Weaver;Walter Beasley', 'Sylvester Weaver']},
"21115":{"count": 56, "artists":['Crystal Gayle', 'Pam Tillis']},
"21145":{"count": 1, "artists":['Larry Stewart']},
"21193":{"count": 49, "artists":['Roscoe Holcomb & The Stanley Brothers', 'The New Lost City Ramblers', 'Roscoe Holcomb']},
"21195":{"count": 1, "artists":['Dwight Yoakam Duet with Maria McKee']},
"21239":{"count": 1, "artists":['John Conlee']},
"22017":{"count": 51, "artists":['Victoria Williams', 'Claude King']},
"22031":{"count": 12, "artists":["Ramblin' Thomas", "Ramblin' Thomas & The Dallas Blues Singers"]},
"22033":{"count": 50, "artists":['Robert Pete Williams & Robert \x1cGuitar" J. Welch', 'Robert Pete Williams']},
"22049":{"count": 54, "artists":['Jimmy Davis', 'Jimmie Davis']},
"22071":{"count": 122, "artists":['The Memphis Minnie', 'Memphis Minnie', 'Papa Charlie Jackson']},
"22123":{"count": 89, "artists":['Jim Oliver', 'Tony Joe White']},
"22125":{"count": 16, "artists":['Theresa Andersson']},
"23021":{"count": 38, "artists":['Jim White', 'Now Is Now']},
"24005":{"count": 15, "artists":['Cheryl Wheeler']},
"25025":{"count": 75, "artists":['Lemonheads', 'Lemonhead', 'The Lemonheads', 'Willard Grant Conspiracy']},
"25027":{"count": 9, "artists":['Drunk Stuntmen']},
"26073":{"count": 6, "artists":['Inner Soul']},
"26161":{"count": 53, "artists":['Bill Kirchen', 'Commander Cody & His Lost Planet Airmen', 'Commander Cody']},
"26163":{"count": 278, "artists":["Bill Haley & Haley's Comets", 'Bill Haley_ The Comets', 'Bill Haley & The Comets', 'Bill Haley', 'Bill Haley & His Comets', 'Bill Haley And The Comets', 'The Velvelettes', 'Bill Haley and his Comets', 'Kim Weston / Marvin Gaye', 'Marvin Pontiac', 'Kim Weston', 'Volebeats']},
"27001":{"count": 21, "artists":['The Blue Jays', 'Martin Zellar']},
"27019":{"count": 2, "artists":['Hank Williams III']},
"27047":{"count": 46, "artists":['Eddie Cochran & Gene Vincent', 'Eddie Cochran with The Holly Twins', 'Eddie Cochran']},
"27053":{"count": 29, "artists":['Skhan', 'The Jayhawks']},
"27109":{"count": 1, "artists":['Joe Sun']},
"28011":{"count": 88, "artists":['Big Bill Broonzy', 'Henry Townsend']},
"28017":{"count": 97, "artists":['Glen Campbell And Bobbie Gentry', 'Bobbie Gentry']},
"28027":{"count": 91, "artists":['John Lee Hooker & Jimmie Vaughn', 'John Hooker', 'Muddy Waters', 'John Lee Hooker & Carlos Santana', 'John Lee Hooker_ Booker T_ Randy California', 'John Lee Hooker']},
"28029":{"count": 101, "artists":['Robert Johnson', 'Robert Lockwood Jr', 'David "Honeyboy" Edwards', 'Bukka White', 'Robert Johnson / Philip Kraus / Chicago Symphony Chorus / Chicago Symphony Orchestra / Sir Georg Solti', 'Pedro Pardo']},
"28033":{"count": 45, "artists":['Cory Branan', 'Robert Wilkins']},
"28049":{"count": 97, "artists":['Robert Johnson', 'Charlie Patton', 'The Mississippi Sheiks', 'Mississippi Sheiks & Chatman Brothers', 'Charlie McCoy', 'Mississippi Sheiks']},
"28075":{"count": 36, "artists":['Ty Herndon;Stephanie Bentley', 'Ty Herndon']},
"28089":{"count": 32, "artists":['Tex Ritter & His Texans', 'Cary Hudson', 'Buffalo Nickel Band']},
"28095":{"count": 32, "artists":['Lucille Bogan']},
"28101":{"count": 12, "artists":['Paul Overstreet']},
"28123":{"count": 10, "artists":['Randy Houser']},
"28143":{"count": 17, "artists":['Doctor Ross']},
"29077":{"count": 75, "artists":['The Jordanaires & Orion', 'The Jordanaires;The Mello Men;Elvis Presley', 'The Jordanaires']},
"29091":{"count": 27, "artists":['Teddy Thompson', 'Jan Howard']},
"29131":{"count": 33, "artists":['DNR Crew Productions', 'Billy Swan with Scotty Moore', 'Billy Swan with Carl Perkins', 'Billy Swan', 'Cumberland Quartet']},
"29135":{"count": 43, "artists":['Gene Clark', 'Dillard & Clark']},
"29159":{"count": 20, "artists":['Leroy Van Dyke & Sylvie', 'Leroy Van Dyke']},
"29187":{"count": 48, "artists":['Ferlin Husky', 'Ferin Husky']},
"30049":{"count": 33, "artists":['Nicolette Larson', 'Nicolette Larson / Michael McDonald']},
"30063":{"count": 27, "artists":['Tarkio']},
"31157":{"count": 13, "artists":['Randy Meisner']},
"33009":{"count": 2, "artists":['Bill Morrissey']},
"34005":{"count": 28, "artists":['The Re-Mains']},
"34021":{"count": 47, "artists":['Mary Chapin Carpenter']},
"34027":{"count": 34, "artists":['Neal Casal']},
"36047":{"count": 147, "artists":["Ramblin' Jack Elliot", 'Eddie Rabbitt', 'Stefan Grossman and Tokio Uchida', "Ramblin' Jack Elliott", 'Stefan Grossman']},
"36059":{"count": 39, "artists":['Audra McDonald', 'Shannon McNally']},
"36061":{"count": 465, "artists":['Davis Coen', 'Young Lords_ Kites_ Prurient', 'Meredith Monk_ Theo Bleckmann_ Ellen Fisher_ Katie Geissinger_ Ching Gonzalez_ Allison Sniffin_ Sash', 'Meredith Monk_ Katie Geissinger', 'Meredith Monk and Vocal Ensemble', 'Meredith Monk', 'Jeff Finlin', "Dan Zanes Feat. Rankin' Don And The Rocket Ship Singers", 'Dan Zanes Feat. Cynthia Hopkins', 'Dan Zanes Feat. Bob Weir', 'Dan Zanes Feat. A Cast Of Thousands!!', 'Dan Zanes Feat. Suzanne Vega', 'Dan Zanes Feat. John Doe', 'Dan Zanes Feat. Aggie Decaul And Courin Gibbs', 'Dan Zanes Feat. Lou Reed And The Rubi Theater Company', 'Dan Zanes Feat. Donald Saaf and The Rocket Ship Singers', 'Dan Zanes Feat. Philip Glass', 'Dan Zanes Feat. Aimee Mann', 'Dan Zanes Feat. Dar Williams', 'Dan Zanes Feat. Sheryl Crow', 'Dan Zanes Feat. The Sandy Girls', "Dan Zanes Feat. Rankin' Don aka Father Goose", 'Dan Zanes Feat. Angelique Kidjo', 'Dan Zanes', 'Dan Zanes Feat. Yoshi Waki', 'Jimmy Durante', 'Art Ensemble Of Chicago', 'Chip Taylor_ Evie Sands', 'Chip Taylor_ Carrie Rodriguez', 'Chip Taylor', 'Patti Rothberg', 'Jolene', 'Amy Allison', 'Joe Lewis  ', 'Dan Zanes Feat. Barbara Brousal', 'Dan Zanes Feat. The Rocket Ship Revue', 'Migue Garcia', 'The Gryphon Trio', 'Unbelievable!', 'Alan Silvestri', 'Lee Roy Parnell']},
"36077":{"count": 72, "artists":['Jerry Jeff Walker', 'Circus Maximus', 'Xavier Mugardos']},
"36081":{"count": 1, "artists":['Kieran Kane']},
"36103":{"count": 25, "artists":['Terry Winchell']},
"37005":{"count": 28, "artists":['Del Reeves', 'Del Reeves & Billie Jo Spears']},
"37007":{"count": 79, "artists":['Blind Boy Fuller']},
"37027":{"count": 26, "artists":['Carl Story', 'Etta Baker']},
"37075":{"count": 95, "artists":['MILSAP_ RONNIE', 'Ronnie Milsap']},
"37123":{"count": 151, "artists":["Tim O'brien", 'The Booth Brothers', 'Malcolm Holcombe', 'Bill Phillips', 'Dove Brothers', 'Daryl Williams Trio']},
"37133":{"count": 96, "artists":['Ryan Adams']},
"37171":{"count": 61, "artists":['Donna Fargo']},
"37193":{"count": 21, "artists":['OLIVER', 'Oliver Dodd']},
"38035":{"count": 27, "artists":['Lynn Anderson', 'Frank Ifield']},
"39049":{"count": 51, "artists":['Two Cow Garage', 'McGuffey Lane']},
"39057":{"count": 45, "artists":['Richie Furay', 'The Richie Furay Band', 'Furay_ Richie Band']},
"39087":{"count": 94, "artists":['Bobby Bare with Jeannie Bare', 'Bill Parsons', 'Bobby Bare_ Norma Jean & Liz Anderson', 'Bobby Bare with Norma Jean & Liz Anderson', 'Bobby Bare']},
"39089":{"count": 22, "artists":['Dallas Moore']},
"39145":{"count": 13, "artists":['Ras Flabba', 'Earl Thomas Conley']},
"39153":{"count": 123, "artists":['David Allan Coe;Bill Anderson', 'David Allan Coe', 'Rachel Sweet']},
"40015":{"count": 18, "artists":['Roy Clark']},
"40023":{"count": 15, "artists":['Ray Wylie Hubbard']},
"40027":{"count": 12, "artists":['Kellie Coffey with Richie McDonald', 'Kellie Coffey']},
"40031":{"count": 50, "artists":['Bryan White']},
"40037":{"count": 7, "artists":['Lee Hazlewood', 'Jack Guthrie & The Oklahomans', 'Jack Guthrie']},
"40049":{"count": 48, "artists":['Roy Milton & His Solid Serenades', 'Milton_ Roy', 'Roy Milton']},
"40057":{"count": 4, "artists":['Glenn Barber']},
"40109":{"count": 49, "artists":['Tommy Overstreet', 'Henson Cargill', 'Jimmy Dean']},
"40119":{"count": 1, "artists":['James Talley']},
"40123":{"count": 59, "artists":['Blake Shelton']},
"40137":{"count": 47, "artists":['Hoyt Axton']},
"40143":{"count": 74, "artists":['Joe Diffie', 'Joe Diffie / Lee Ann Womack', 'The Tractors']},
"41013":{"count": 42, "artists":['Richmond Fontaine', 'Billy Joe Shaver', 'Mickey Newbury']},
"41017":{"count": 55, "artists":['Sani', 'Reckless Kelly']},
"41047":{"count": 39, "artists":['Joaquin Phoenix/Reese Witherspoon', 'Joaquin Phoenix', 'Dolorean']},
"42017":{"count": 4, "artists":['Illinois']},
"42027":{"count": 1, "artists":['P.I.M.P.']},
"42037":{"count": 44, "artists":['Lacy J. Dalton']},
"42055":{"count": 28, "artists":['Ed McCurdy']},
"44007":{"count": 19, "artists":['Paul Geremia', 'Geremia', 'The Lively Ones', 'Kent', 'Frederic de Roos']},
"45003":{"count": 73, "artists":['Faulconer_ Bruce', 'John Berry']},
"45019":{"count": 23, "artists":['Darius Rucker']},
"45059":{"count": 56, "artists":['Rev. Blind Gary Davis', 'Sidonio Pereira', 'The New Lost City Ramblers', 'Blind Gary Davis', 'Reverend Gary Davis', 'Rev. Gary Davis']},
"45075":{"count": 54, "artists":['Davis Coen', 'John Amen']},
"45083":{"count": 1, "artists":['The Marshall Tucker Band']},
"45087":{"count": 12, "artists":['Peg Leg Sam featuring Louisiana Red', 'Peg Leg Sam']},
"46027":{"count": 91, "artists":['Shawn Colvin']},
"47009":{"count": 26, "artists":['Jack Greene', 'Jimmy Cliff']},
"47015":{"count": 392, "artists":['Sara Evans & Bethany Olds', 'Sara Evans', 'Will Kimbrough', 'Madi Diaz', 'Richie McDonald', 'The Burn', 'Yankee Grey', 'Mila Mason', 'Stephen Simmons', 'Legacy Five/Roger Bennett', 'Legacy Five', 'George Hamilton IV & Sylvie', 'Joe Stampley', 'Joe Sample', 'Area Code', 'Bob Cheevers', 'Sid Selvidge', 'Karen Taylor-Good', 'Karen Taylor Good', 'R.B. Morris', 'George Younce', 'Lauren Talley', 'Lauren Talley/Joy Gardner', 'My Drug Hell', 'Tre Om Taube', 'Karen Peck And New River', 'Karen Peck & New River', 'Kirk Talley', 'Marthia Sides', 'Debra Talley', 'George Hamilton IV', 'Joanna Cotten']},
"47037":{"count": 233, "artists":['Big & Rich (With Gretchen Wilson And Cowboy Troy)', 'Big Rich', 'Nicolette Larson', 'Laura Cantrell', 'Gillian Welch', 'Original Size', 'Gillian Welch & David Rawlings', 'Nikolaus Harnoncourt & Concentus musicus Wien', 'Lambchop', 'Loretta Lynn / Conway Twitty', 'Doug Hoekstra', 'Big & Rich']},
"47053":{"count": 50, "artists":['T.G.Sheppard', 'T.G. Sheppard']},
"47075":{"count": 26, "artists":['Yank Rachell', 'Yank Rachel']},
"47079":{"count": 34, "artists":['Hank Williams Jr. / Lois Johnson', "Your Cheatin' Heart: Orignial Motion Picture Soundtrack", 'HANK WILLIAMS_ JR.', 'Merle Kilgore', 'Hank Williams Jr.']},
"47081":{"count": 8, "artists":['Minnie Pearl']},
"47085":{"count": 33, "artists":['George Candy', 'George Morgan']},
"47097":{"count": 99, "artists":['Sleepy John Estes & John Henry Barbee', 'Sleepy John Estes']},
"47149":{"count": 39, "artists":['The Boomers']},
"47153":{"count": 10, "artists":['Cody McCarver']},
"47155":{"count": 10, "artists":['Stella Parton']},
"47157":{"count": 209, "artists":['William Bell / Judy Clay', 'William Bell', 'Deborah Allen', 'Woody Herman & His Orchestra', 'Frank Stokes', 'Dorsey Burnette', 'Anita Kerr']},
"47163":{"count": 15, "artists":['Doyle Lawson & Quicksilver']},
"47165":{"count": 76, "artists":['The Oak Ridge Boys', 'Ronnie McDowell', 'Oak Ridge Boys']},
"47185":{"count": 28, "artists":['Benny Martin']},
"47189":{"count": 93, "artists":['The Charlie Daniels Band', 'Charlie Daniels']},
"48001":{"count": 2, "artists":['Kinky Friedman', 'AP9']},
"48013":{"count": 1, "artists":['Rodney Hayden']},
"48029":{"count": 72, "artists":['Rosie Flores', 'HOLLY DUNN']},
"48037":{"count": 3, "artists":['Little Hat Jones', 'Special EFX']},
"48067":{"count": 12, "artists":['Nat Stuckey & Connie Smith']},
"48073":{"count": 48, "artists":['Neal McCoy']},
"48095":{"count": 392, "artists":['The Kyle Bennett Band', 'Denim', 'Honeybrowne', 'Blind Lemon Jefferson', 'Blue Edmondson W/ Matt Powell', 'Homer', 'Lee Roy Parnell', 'The Longest Day', 'Sons of Perdition', 'Mancy', 'Owen Temple', 'Colin Gilmore', 'Gurf Morlix', 'Mark Monaco', 'Tex Williams', 'Tex Ritter & His Texans', 'Tex Ritter', 'The Legendary Stardust Cowboy', 'Trish Murphy', 'Tim Rushlow', 'Bessie Tucker', 'The Damnations', 'Bruce Robison', 'Jim Hightower', 'Tex Rifter']},
"48113":{"count": 232, "artists":['Michelle Shocked', 'Eppu Normaali', 'Cowboy Troy (Featuring Big & Rich)', 'Kira B.M.J.', 'Cowboy Troy (With ATOM)', 'Cowboy Troy', 'Cowboy Troy (With Big & Rich)', 'Cowboy Troy (With Jon Nicholson)', 'Cowboy Troy (With James Otto)', 'Cowboy Troy (With Tim McGraw and Big Kenny)', 'Cowboy Troy (With Sarah Buxton)', 'Michael Martin Murphey', 'Michael Murphey', 'Hans Petter Hansen', 'B.W. Stevenson', 'Lillian Glinn', 'Stephen Stills']},
"48141":{"count": 29, "artists":['Tom Russell & Dolores Keane', 'Kari Bremnes', 'Tom Russell & Andrew Hardin', 'Knut Reiersrud', 'Pigalle Guitar Ensemble', 'Tom Russell', 'Tom Russell & Iris Dement', 'Ait Challal', 'Iris Dement', 'Dave Van Ronk', 'Iris Dement & Kari Bremnes', 'Sondre Bratland', 'Sondre Bratland & Iris Dement', 'Dolores Keane']},
"48165":{"count": 107, "artists":['Tanya Tucker / Glen Campbell', 'Tanya Tucker', 'Adolphson & Falk']},
"48181":{"count": 82, "artists":['Gene Autrey', 'Gene Autry']},
"48189":{"count": 43, "artists":['Jimmy Dean']},
"48201":{"count": 18, "artists":['Michael Nesmith', "Rich O'Toole"]},
"48245":{"count": 140, "artists":['Clay Walker', 'Billie Jo Spears', 'Billy Jo Spears', 'Billie Jo  Spears']},
"48279":{"count": 72, "artists":['Waylon Jennings and the Waylors', 'Waylon Jennings & The Waymore Blues Band', 'Waylon Jennings;Willie Nelson;Johnny Cash;Kris Kristofferson', 'Waylon Jennings', 'John Anderson / Waylon Jennings']},
"48303":{"count": 39, "artists":['Joe Ely', 'Butch Hancock', 'Daron Norwood']},
"48315":{"count": 10, "artists":['Stuart Hamblen']},
"48347":{"count": 28, "artists":['Bob Luman']},
"48355":{"count": 2, "artists":['Louise Mandrell;Eric Carmen', 'Louise Mandrell']},
"48365":{"count": 136, "artists":['James Reeves', 'Jim Reeves']},
"48401":{"count": 15, "artists":['Claude Gray']},
"48437":{"count": 28, "artists":['Dale Watson', 'Jimmie Dale Gilmore']},
"48439":{"count": 105, "artists":['Townes Van Zandt', 'Townes Zandt', 'Katy Moffatt', 'Gary Morris']},
"48453":{"count": 43, "artists":['England Dan & John Ford Coley']},
"48461":{"count": 50, "artists":['DAN SEALS']},
"48475":{"count": 32, "artists":['Guy Clark']},
"49039":{"count": 11, "artists":['Ned Miller']},
"51017":{"count": 66, "artists":['June Carter Cash', 'Carla', 'Kate Maki', 'Sons Of Bill', 'Anita Carter_ Helen Carter_ June Carter Cash', 'Cleve Francis']},
"51087":{"count": 30, "artists":['Smokey Wilson']},
"51157":{"count": 54, "artists":['John Jackson']},
"51171":{"count": 13, "artists":['Danni Leigh']},
"51173":{"count": 11, "artists":['Clay Davidson']},
"51590":{"count": 51, "artists":['Ricky Van Shelton']},
"51680":{"count": 11, "artists":['Ray Pillow']},
"51720":{"count": 48, "artists":['Old Man Tha Husla', 'Dock Boggs']},
"51760":{"count": 26, "artists":['Wrinkle Neck Mules']},
"51810":{"count": 31, "artists":['Juice Newton']},
"51830":{"count": 2, "artists":['Jimmy Fortune_ Dailey & Vincent']},
"53033":{"count": 98, "artists":['Supersuckers', 'Electric Frankenstein', 'The Supersuckers', 'Bonnie Guitar']},
"54097":{"count": 11, "artists":['The New Relics']},
"55025":{"count": 51, "artists":['Mother Earth', 'Tracy Nelson']},
"55073":{"count": 2, "artists":['Jeffrey Foucault', 'Those Poor Bastards']},

}
