var rock = {
"01001":{"count": 16, "artists":['VULTURE WHALE', 'Travis Wammack', 'Sailcat']},
"01033":{"count": 39, "artists":['Viva Voce', 'Mo', 'Shenandoah']},
"01073":{"count": 290, "artists":['Taylor Hicks', 'Emmylou Harris with Gram Parsons', 'Celine Frisch', 'Emmylou Harris with Dolly Parton and Linda Ronstadt', 'Emmylou Harris with Ricky Skaggs', 'Earl Thomas Conley;Emmylou Harris', 'Emmylou Harris', 'Emmylou Harris / Alison Krauss / Gillian Welch', 'Mary Black Feat. Emmylou Harris & Dolores Keane', 'Maylene & The Sons Of Disaster', 'Maylene And The Sons Of Disaster', 'Maria Taylor with Andy LeMaster', 'Thought It Over', 'Dan Sartain', 'Maria Taylor', 'The Rewinds', 'Bill Justis', 'Ken Macintosh', 'Hardrock Gunter', 'Jimmy Murphy', 'Science Verses Romance']},
"01075":{"count": 1, "artists":['Dan Penn & Donnie Frits']},
"01077":{"count": 49, "artists":['Sam Phillips', 'Leslie Phillips']},
"01089":{"count": 5, "artists":['Cassino', 'Cassino & Laben']},
"01097":{"count": 36, "artists":['Hurriganes', 'Wet Willie', 'Anthony Watson']},
"01101":{"count": 72, "artists":['Dr Feelgood', 'Tommy Shaw', 'Dark Pink Moon', 'KRS-1', 'Toni Tennille']},
"01103":{"count": 3, "artists":['The Sam Lay Blues Band', 'Palmera']},
"02020":{"count": 1, "artists":['The Long Winters']},
"02090":{"count": 13, "artists":['Rick Holmstrom']},
"02170":{"count": 4, "artists":['Tito & Tarantula', 'Tito And Tarantula']},
"04007":{"count": 7, "artists":['Dope Aviators', 'Gila']},
"04013":{"count": 193, "artists":['Stevie Nicks & Don Henley', 'Stevie Nicks / Tom Petty And The Heartbreakers', 'Stevie Nicks w/ Tom Petty and the Heartbreakers', 'Stevie Nicks', 'Until June', 'Marty Robbins', 'Bissen', 'Jessi Colter', 'Music Makers']},
"04019":{"count": 218, "artists":['Arcade Fire', 'Calexico', 'Linda Ronstadt & Emmylou Harris', 'Linda Ronstadt featuring Aaron Neville', 'Linda Ronstadt with James Taylor', 'The Stone Poneys', 'James Ingram;Linda Ronstadt', 'Green On Red', 'Friends Of Dean Martinez', 'Linda Ronstadt']},
"04025":{"count": 125, "artists":['Trik Turner', '32 Leaves', 'H.e.a.t', 'Merci Miss Monroe', 'Chaotica', 'Prodigal', 'Fivespeed', '24 Hours', 'Five Speed', 'Army of Robots', 'Todd Herzog', 'Boreas', 'Gas Giants', 'Grace Overthrone']},
"05003":{"count": 40, "artists":['K.T. Oslin', 'K T Oslin']},
"05023":{"count": 5, "artists":['Wayne Raney']},
"05027":{"count": 12, "artists":['Larry McCray']},
"05031":{"count": 101, "artists":["Jim Dandy's Black Oak Arkansas", 'Black Oak Arkansas', "Jim Dandy's Black Oak_ Arkansas"]},
"05047":{"count": 43, "artists":['Roy Buchanan']},
"05049":{"count": 35, "artists":['Jaded Heart']},
"05055":{"count": 50, "artists":['Home Of The Lame', 'Iris Dement']},
"05087":{"count": 25, "artists":['Andy Starr']},
"05107":{"count": 32, "artists":['Cedell Davis']},
"05109":{"count": 83, "artists":['Gladys Knight', 'Glen Campbell', 'Turisas']},
"05115":{"count": 20, "artists":['Deas Vail']},
"05119":{"count": 268, "artists":['Dan Hicks & His Hot Licks', 'Dan Hicks and The Accoustic Warriors', 'Dan Hicks', 'American Princes', 'Dale Hawkins', 'Billy (Lee) Riley', 'Billy Lee Riley', 'Third Degree', 'Joy Lynn White', 'Larry Donn', 'Tony Spinner', 'Trout Fishing in America']},
"05125":{"count": 94, "artists":['Charlie Rich']},
"05133":{"count": 91, "artists":['Collin Raye;Joe Diffie', 'Collin Raye']},
"05139":{"count": 83, "artists":['Sleepy LaBeef']},
"05143":{"count": 32, "artists":['The Cate Brothers']},
"05145":{"count": 82, "artists":['Union', 'The Gossip / Tracy and the Plastics', 'Envoy', 'The Gossip', 'Gossip']},
"06001":{"count": 274, "artists":['Audrye Sessions', 'Creedence Clearwater Revival', 'John Fogerty / Don Henley / Timothy B. Schmit', 'John Fogerty / Bruce Springsteen', 'John Fogerty', 'The Answer', 'Oversol', 'Gun', 'Gun & Gore', 'Fleshies', 'Sir Thomas Allen/Geoffrey Parsons', 'Alvin Youngblood Hart', 'Bill Champlin', 'Timothy B. Schmit', 'Preston Epps', 'Edwin Hawkins']},
"06013":{"count": 88, "artists":['I The Mighty', 'Cliffhanger', 'Shadow Circus', 'Mark Eitzel']},
"06019":{"count": 1025, "artists":['Ben Harper And The Innocent Criminals', 'Ben Harper', 'Ben Harper And Relentless7', 'The Album Leaf', 'This Will Destroy You', 'The Sound Of Animals Fighting', 'Hollywood Undead', 'Ozma', 'Ozma & DJ Art', 'Potluck', 'Iration', 'Get Back Loretta', 'Samiam', 'Throwing Muses', 'Lost Ocean', 'The Henry Clay People', 'The Paradigm', 'Paradigm', 'Seed : Jocelyn Soler_ Philippe Elter_ Florent Elter_ Romain Dubuis', 'The Seed', 'Seed', 'Idaho', 'Loggins & Messina', 'Loggins And Messina', 'Vera', 'Vera & Federico Molinari', 'Ian Moore', 'Ian Moore_ Lossy Coils', 'Martin Simpson_ Danny Thompson', 'Martin Simpson_ Jessica Simpson', 'Martin Simpson_ Keith Angel_ Danny Thompson_ BJ Cole_ Andy Cutting_ Muireann Nic Amhlaoibh', 'P Ramlee', 'Martin Simpson', 'Montrose', 'Kite Flying Society', 'Think', 'Vivid', 'Dj Vivid', 'Brown Shoe', 'Revere', '13 Cats', 'Khymera', 'Adam Watts/Andy Dodd', 'Adam Watts', 'deccatree', 'See Spot Run', 'mechanical bride', 'The Nucleus', 'Thomas Cunningham', 'Collins Kids (Larry & Lorrie)', 'Collins Kids', 'The Collins Kids', 'Doc Holliday', 'Broken English', 'The Paper Champions', 'The Flowers Of Hell', 'Binocular', 'Dj Logilo', 'Rancho Deluxe', 'Tomihira', 'The Clock Work Army', 'Sciflyer', "Let's Get Out of This Terrible Sandwich Shop", 'Lets Get Out Of This Terrible Sandwich Shop', 'Faxed Head', 'Kathy Ross', 'The Wesley Willis Fiasco', 'Sweethearts of the Rodeo;David Allan Coe', 'Peel', 'Mick Overman', 'Trespassers William', 'Star Off Machine', 'Ron Elliott', 'Negative', 'Chris Gaffney and the Cold Hard Facts', 'International Artists', 'Mercury Bullet']},
"06029":{"count": 15, "artists":['Memphis May Fire']},
"06037":{"count": 6029, "artists":['Jay-Z / Linkin Park', 'The Doors', 'Beck And Allen', 'Beck_ Bogart_ Appice', 'Beck / Jay-Z / Pharrell Williams', 'Beck & Emmylou Harris', 'Beck', 'Poison Idea', 'Gas Huffer', 'The Offspring', 'Enrico Musiani', 'Flogging Molly', 'Tom Waits', 'Tom Waits;Crystal Gayle', 'Liars', 'Velvet Revolver', 'Year Long Disaster', 'Bullets And Octane', 'The Doobie Brothers', 'The Turtles', 'Tenacious D', 'Styx', 'UNKLE', 'Autolux', 'Foreign Born', 'Stephen Malkmus', 'Stephen Malkmus & The Jicks', 'Bjlsen Valsemlle', 'Health', 'Los Lobos & Money Mark', 'Los Lobos', 'Love with Arthur Lee', 'Love & Tears', 'Love', 'O.P.M', 'I HEART HUCKABEES', 'The Gunclub', 'James Horner', 'James Horner;London Symphony Orchestra', 'James Horner;Rahat Nusrat Fateh Ali Khan', 'The Little Ones', 'Anomia Blues Band', 'Canned Heat And John Lee Hooker', 'Carl Anton/Hans Wahlgrens Orkester', 'Canned Heat', "The Go-Go's", 'Kari Hansa & Gregers Hes', 'Little Feat', 'Little Feat (With Linda Ronstadt)', 'Crossroads / Ry Cooder', 'Ry Cooder with Cesar Rosas & David Hidalgo', 'Konstantinos Karamanlis', 'Ry Cooder with Lee Ving', 'Mahlathini and the Mahotella Queens', 'F/i', 'Earlimart', 'Hot Water Music', 'We Are The Fury', 'Dolor', 'Frank Black', 'Dalia', 'Frank Black & Gary U.S. Bonds', 'David Ryan Harris', 'Colour', 'The Daylights', 'Coasters', 'The Coasters', 'Sparks', 'Sparks / Oschino', 'Red Sparowes', 'Beatriz Marquez', 'Three Bad Jacks', 'Bread feat. Call Back', 'Bread', 'Flying Burrito Brothers', 'Zarama', 'The Flying Burrito Brothers', 'Mika Miko', 'Paul Revere & The Raiders', 'The Grassroots', 'Symphonic Hits', 'The Germs', 'Germs', 'The Blood Arm', 'Mondo Generator', 'Nick Oliveri of Queens of the Stone Age presents Mondo Generator', 'Glenn Hughes', 'Million Dollar Mouth', '& etc', 'Ritchie Valens', 'Keaton Simons', 'Thee Sixpence', 'Strawberry Alarm Clock', 'Radio 4', 'Los Hijos de Juana Gallo', 'Breakout', 'The BellRays', 'Christian Death', 'Christian Death Featuring Rozz Williams', 'Christian Death Presents', 'Concrete Blonde', 'Totimoshi', 'Dominique Vellard', 'Vitamin String Quartet', 'Rocazino', 'Omnia', 'Captain & Tennille', 'Overnight Lows', 'The Electric Prunes', 'The Lost', 'Lavender Diamond', 'Lords Of Altamont', 'Johnny Horton', 'Michael Aston', 'Gene Loves Jezebel', 'Fuiasko', 'Dr.M.Balamuralikrishna', 'The Seeds', 'Dan Bern', 'Joe Firstman', 'Harold B', 'Red Sun_ SamulNori', 'The London Fox Players', 'Harold Budd And Eugene Bowen', 'Harold Budd And Chas Smith', 'The Lonnie Donegan Band', 'Harold Budd_ Clive Wright', 'Harold Budd', 'Niacin', 'Steve Lukather', 'Bird York', 'Midnight Movies', 'The Association', 'Russ Giguere from The Association', 'Grant Lee Buffalo', 'Ambrosia', 'Coro e Orchestra Della Cappella Musicale di S. Petronio', 'Gilby Clarke', 'The Surfaris', 'The Champs', 'CHAMPS', 'Coyote Shivers', 'Ira Maria Witoschynskyj', 'Stavesacre', 'Dread Zeppelin', 'Poco', 'Coco Montoya', 'Silver', 'Upsilon Acrux', 'Marlene', 'Marlene_ Severino Araujo Orquestra', 'Marlene_ Severino Araujo_ Orquestra Tabajara', 'M6', 'The Standells', 'Beth Gibbons / Rustin Man', 'Kofi', 'Tony Curtis', 'Red Snapper feat. MC Det', 'Carl Smith', 'Telecast', 'Valet', 'Xu Xu Fang', 'Controlling the Famous', 'Margo Guryan', "Ariel Pink's Haunted Graffiti", 'Elvin Bishop', 'Fair Warning', 'Omni', 'Carbon Silicon', 'Tanja', 'Bob D', 'Aces High', 'Cliff Eidelman', 'Dole & Kom pres. Sona', 'Sanchez', 'Bob Welch', 'Emitt Rhodes', 'Angel City Outcasts', 'Whistler', 'Tony Furtado', 'Tony Furtado And The American Gypsies', 'Blue', 'Eleven', 'David Pack', 'Theodore', 'Betty Blowtorch', 'Delta Nove', 'Debbie Davies_ Chris Layton & Tommy Shannon', 'Common Rotation', 'Shameless', 'opm', 'Zolar X', 'Zolar-X', 'Joe Byrd & The Field Hippies', 'David Scott', 'Knuckles', 'Ari Shine', 'Anna Waronker', 'Mephisto Walz', 'Hamilton_ Joe Frank & Reynolds', 'Little Caesar', 'Rod Piazza & The Mighty Flyers', 'Dwarves', 'Karla Bonoff', 'Screams For Tina', 'SLAPBAK', 'The Zeros', 'MCM feat. C-LONE', 'MCM', 'Steve Wynn', 'Steve Wynn & Linda Pitmon', 'Steve Wynn & The Dragon Bridge Orchestra', 'Mike Post feat. Larry Carlton', 'Odelia', 'Odelia_ Anita', 'Philip Sayce', 'Wishful Thinking', 'KORE featuring KORE', 'KORE', 'Amy Cook', 'The Flash Express', 'Gilli Moon', 'Brewer & Shipley', 'Ben Vaughn', 'Rain Parade', 'The Rain Parade', 'The Prime Movers', 'Texture', 'Prymary', 'Lauren Wood', 'Blood On The Saddle', 'Flaming Stars', 'The Flaming Stars', 'Ill Lit', 'Los Hermanos Dalton', 'The Premiers', 'Carole Pope', 'Joboj', 'Thee Midniters', 'Biblical Proof Of UFOs', 'The Gurus', 'Gloria Loring', 'The Special Goodness', 'Steven R. Smith', 'Randy Weeks', 'Eggshell Egoz', 'AllRise', 'Riff Raff', 'Brasstacks', 'Brass Tacks', 'Year Of The Rabbit', 'Amar Kobbi', 'Soulution', 'Lost On Purpose', 'Jonny Polonsky', 'The Geraldine Fibbers', 'Leaving Trains', 'Holly Beth Vincent', 'Bobby Sherman', 'National Dust', 'Chris Hillman', 'Chris Hillman & Herb Pederson', 'Sandy Nelson', "Alan O'Day", 'The Lazy Cowgirls', 'Faust', 'Jo Jo Gunne', 'The Morgans', 'Philip Bardowell', 'Brandon Schott', 'Steve Fister', 'Non Credo', 'Peppermint Creeps', 'The Boxmasters feat. Billy Bob Thornton', 'The Four Preps', 'Four Preps', 'Curt Boetcher', 'Interstate Blues', 'Josh Link_ DJ Garon', 'DJ Garon', 'Radio Free America', 'Nick Duffy', 'Alien Breed', 'The Weather Underground', 'Jody Reynolds', 'The Gun Club', 'Gun Club', 'Kim Fox', 'Jay Ferguson', 'The Stone Poneys Featuring Linda Ronstadt', 'The Stone Poneys', 'Jack Irons', 'Tuggawar', 'El Pino & the Volunteers', 'Wckr Spgt', 'The Flesh Eaters', 'Shelby Flint', 'O Rappa', "D'Molls", 'Ry Cooder', 'Snakefarm', 'Ceramic Holiday', 'Tyler Hilton', 'Tindrum', 'Southern Pacific', 'Gene Parsons', 'Speedbuggy USA', 'The Pastel Six', 'Melora Hardin', 'Kurt Tepperwein', 'Adam Ray', 'Lazlo Bane', 'Kane', 'Abner Burnette', 'Los Lobos with Antonio Banderas', 'Greg Dulli', 'The Nightwatchman', 'Debbie Davies', 'Pete G', 'The Grass Roots', 'Highway 101', 'Jean-Luc Ponty']},
"06045":{"count": 89, "artists":['Robben Ford', 'Robben Ford / Susan Tedeschi', 'Slaves To Gravity']},
"06053":{"count": 32, "artists":['Sammy Hagar']},
"06057":{"count": 19, "artists":['Bjornemyr', 'Advantage', 'The Advantage']},
"06059":{"count": 225, "artists":["Jack's Mannequin", "Jack's Mannequin featuring Mick Fleetwood", 'Dustin Kensrue', 'Project 86', 'The Willowz', 'Willowz_ The', 'They Might Be Giants', 'TSOL', 'T.S.O.L.', 'The Chantays', "Chantay's", 'The Colour', 'Shelleyan Orphan']},
"06065":{"count": 48, "artists":['The Scaramanga Six']},
"06067":{"count": 109, "artists":['Billy Corgan', 'Limbeck', 'Hella', 'Groovie Ghoulies', 'Looking Glass', 'Nil Lara', 'Roger Voudouris']},
"06073":{"count": 497, "artists":['Switchfoot', 'The Soft Pack', 'Tristeza', 'Emma Kirkby / The Academy of Ancient Music / Christopher Hogwood', 'Mickie Krause', 'Louis XIV', 'Waking Ashland', 'Iron Butterfly', 'Ann Wilson / Rufus Wainwright / Shawn Colvin', 'Ann Wilson', 'Ann Wilson / Nancy Wilson / Deana Carter / Wynonna', 'Ann Wilson / Wynonna', 'Ann Wilson / Elton John', 'Ann Wilson / Nancy Wilson', 'Ann Wilson / Alison Krauss', 'Ann Wilson;Nancy Wilson', 'Ann Wilson / k.d. lang', 'Ann Wilson / Gretchen Wilson', 'We Shot the Moon', 'Rocket From The Crypt', 'Abra Moore', 'The Transit War', 'Pacific Ocean Fire_ Naim Corteze', 'Pacific Ocean Fire', 'Noise Ratchet', 'Mike Keneally', 'MIKE KENEALLY & BEER 4 DOLPHINS', 'Barbara Manning', 'Barbara Manning & The Go-Luckys!', 'Lesser', 'Riserva Moac', 'The Beat Farmers', 'Granfaloon Bus', 'Pinback']},
"06075":{"count": 1952, "artists":['T-Rain', 'FBOM', 'Train', 'Santana featuring Eric Clapton', 'Santana Feat. Rob Thomas', 'Sisa', 'Mr. Vyrus', 'Santana featuring Mana', 'Santana Featuring Chad Kroeger', 'Jefferson Airplane', 'Brian Jonestown Massacre', 'The Brian Jonestown Massacre', 'The Dodos', 'Deerhoof', 'Theo Eastwind', 'Flipper', 'Two Gallants', 'Thee More Shallows', 'The Action Design', 'Mud', 'Yeti', 'Jefferson Starship', 'Janis Joplin', 'Big Brother & The Holding Company;Janis Joplin', 'DJ Mindforce', 'Big Brother & The Holding Company (featuring Janis Joplin)', 'Big Brother & The Holding Company', 'Big Brother / The Holding Company', 'Yuppie Flu', 'Mark Kozelek', 'Moby Grape', 'American Music Club', 'The Mother Hips', 'Quicksilver Messenger Service', 'Every Move A Picture', 'LoveLikeFire', 'Jerry Garcia;David Grisman;john kahn', 'Jerry Garcia;Mickey Hart', 'Merl Saunders / Jerry Garcia', 'Merl Saunders / Jerry Garcia / John Kahn / Bill Vitt', 'Jerry Garcia / Merl Saunders / John Kahn / Bill Vitt', 'Gratitude', 'Beau Brummels', 'The Beau Brummels', 'Von Iva', 'Acid King', 'Hot Tuna', 'Juniper', 'The Juniper Band', 'The Management', 'The Orange Peels', 'Santana', 'Oranger', 'J Church', 'Lana Lane', 'Go Kart Mozart', 'Go-Kart Mozart', 'Keith Varon', 'Birds & Batteries', 'Ride The Blinds', 'Johnny Lima', 'Kiosk', 'The Kiosk', 'A Minor Forest', 'Citizens Here and Abroad', 'Sugar Blue_ Cathy Richardson', 'Jake Holmes', 'The Horses', 'Alien Crime Syndicate', 'Rocket Scientists', 'Saving Jane', 'The Killers', 'Pirate Radio', 'Tyrone', 'The Jet Set', 'The Lords', 'The Very Hush Hush', 'We Be the Echo', 'Ara', 'ARA vs Amy W', 'ARA & Becka', 'ARA and Becka', 'DJ Ara feat. Kool Savas', 'ARA vs Britney', 'Jinx Jones', 'Everything Must Go', 'Means', 'Thinking Fellers Union Local 282', 'Zonk', 'Hudson Bell', 'Tarnation', 'Mandible Chatter', 'Sopwith Camel', 'The Sopwith Camel', 'Rodger Collins', 'Virgil Deuce', 'Paul Kantner;Grace Slick', 'Paul Kantner', 'The Cult Inside My Head', 'Lodi', 'Magnatune Compilation', 'Anup', 'Orixa', 'Terry Scott', 'Linhart & Jackman', 'Beulah', 'Bob Weir', 'The Red Thread', 'Mind Furniture', 'Steel Rain']},
"06077":{"count": 1, "artists":['Lume']},
"06079":{"count": 87, "artists":['Brenda Holloway', 'Watashi Wa', 'Joose']},
"06081":{"count": 111, "artists":['Second Hand Serenade', 'Secondhand Serenade', 'Funeral Diner', 'Sharimah', 'Neal Schon', 'Keith Carradine']},
"06083":{"count": 52, "artists":['Sugarcult', 'Bad Astronaut']},
"06085":{"count": 91, "artists":['Xiu Xiu/Dead Science', 'XIU XIU', 'Count Five', 'The Count Five', 'Linus Project', 'Puppet Show', 'Puppetshow']},
"06087":{"count": 122, "artists":['Comets On Fire', 'Camper Van Beethoven', 'Mystic Chords of Memory', 'Donny McCaslin']},
"06089":{"count": 12, "artists":['Ashley Parker Angel']},
"06097":{"count": 51, "artists":['Diesel Boy']},
"06099":{"count": 75, "artists":['Brett Dennen / Femi Kuti', 'Brett Dennen', 'GRANDADDY', 'Worth Dying For']},
"06107":{"count": 1, "artists":['Tom Johnston']},
"06111":{"count": 2, "artists":['Ten Foot Pole', '59 Times the Pain']},
"06113":{"count": 53, "artists":['Thin White Rope', 'Middle Of The Road']},
"08003":{"count": 23, "artists":['Michael Johnson']},
"08013":{"count": 162, "artists":['Jello Biafra_ Randy Bachman_ Chris Houston_ and Garnet Sweatshirt', 'DJ Nukem & Marrocco', 'Jello Biafra with The Melvins', 'Firefall', 'Jello Biafra', 'Great American Taxi', 'Hamster Theatre']},
"08031":{"count": 97, "artists":['The Fray', 'Brave Saint Saturn', 'Ghost Buffalo', 'Sods']},
"08059":{"count": 1, "artists":['Randy Van Warmer']},
"08093":{"count": 166, "artists":['Consuption', 'Mama', 'Hercules & Love Affair', 'Hercules', 'Kommune Kreuzberg', 'Hercules And Love Affair', 'Marah', 'Gary Wilson', 'Fred Eaglesmith', 'Rising Sons', 'Happy Birthday', 'D. Biddle']},
"09001":{"count": 4, "artists":['Fake ID', 'Dent']},
"09003":{"count": 23, "artists":['Al Anderson']},
"09009":{"count": 345, "artists":['The Carpenters', 'Karen Carpenter', 'Blood Has Been Shed', 'The Clogs', 'Tyondai Braxton', 'Julliet', 'Ten Shekel Shirt', 'Kath Bloom', 'Bomb Squad', 'Double Negative', 'Rahim Quazi', 'The Mockingbirds', 'The Child Molesters', 'Carpenters', 'The Mustangs', 'Crawling Chaos', 'The Detergents', 'Mark Hummel', 'Peter Blegvad']},
"09011":{"count": 46, "artists":['Animal Collective', 'Arab On Radar']},
"10001":{"count": 25, "artists":['Aidan Baker']},
"10003":{"count": 47, "artists":['George Thorogood & The Destroyers', 'George Thorogood And The Destroyers', 'George Thorogood']},
"11001":{"count": 848, "artists":['Tim Buckley', 'Laura Veirs and Saltbreakers', 'Everything_ Now!', 'Everything', 'The Dismemberment Plan', 'Dismemberment Plan', 'Michael Packer Blues Band', 'kava kon', 'Terry Jacks', 'Fastbacks', 'Stealers Wheel', '7 Year Bitch', 'Screaming Trees', 'Cibo Matto', 'Wilco', 'They Might Be Giants', 'Pilot', 'Spacehog', 'Michael Penn', 'Joan Osborne', 'Brownsville Station', 'Gary Glitter', 'King Missile', 'box and cox publications', 'Soul Coughing', 'Box', 'The Lemonheads', 'George Baker Selection', 'Weezer', 'Letters To Cleo', 'The Muffs', 'Rokker Zsolti', 'Glen Campbell', 'Todd Rundgren', 'Bay City Rollers', 'Natalie Merchant', 'Bad Religion', 'Maria Muldaur', 'Lynn Anderson', 'Morris Albert', 'Hanson', "Gilbert O'Sullivan", 'The Sundays', 'Alice Cooper', 'Ash', 'Bachman Turner Overdrive', 'Babes In Toyland', 'Fountains Of Wayne', 'Dandy Livingstone', 'Desmond Dekker', 'The Shortwave Set', 'Faraquet', 'Mother', 'The Mother', 'Point One', 'Frodus', 'Alex Bello', 'The Sprites', 'Portland State Univ. Chamber Choir & Orchestra', 'Sweet Honey In The Rock', 'Velocity Girl', 'Feral Children', 'Coffin Break', 'Jorma Kaukonen;Tom Hobson', 'Jorma Kaukonen with Tom Hobson', 'Bluetip', 'Jorma Kaukonen', 'Danny Gatton', 'Casual Dots', 'The Caribbean', 'By The Way', 'The Turn-Ons', 'Max Greger & Orchester', 'Air Miami', 'Jing Yin Fang', 'Bridget St John', 'Bridget St. John', 'Paul Burch', 'Blowoff', 'The Transmissionary Six', 'Sprites', 'Memphis Radio Kings', 'Tony Thomas', 'Andrew Gorczyca', 'Unruly Child', 'Mike Shupp', 'Just Plain Darin', 'Honey Tongue', 'Morpheus Project', 'Titan', 'EverAfter', 'Colin Spring', 'Tea Cozies', 'Soundscape']},
"12001":{"count": 62, "artists":['Hot Water Music', 'The Mercury Program', 'Frankie Yankovic', 'Don Felder']},
"12005":{"count": 1, "artists":['Dan Peek']},
"12009":{"count": 18, "artists":['Green Light', 'Greenlight']},
"12011":{"count": 56, "artists":['Pal Utcai Fiuk', 'Saigon Kick']},
"12031":{"count": 260, "artists":['Yellowcard', 'Casey Jones', 'Molly Hatchet', 'Scott McKenzie', 'Karolis featuring Cecilia', 'Gary U.S. Bonds', 'Dickey Betts', 'Rex Smith', 'Johnny Van Zandt', 'Jo Ann Campbell', 'JoAnn Campbell']},
"12039":{"count": 70, "artists":['Billy Dean']},
"12057":{"count": 156, "artists":['Windsor For The Derby', 'This Final Frame', 'CORDALIS_COSTA', 'Pam Tillis', 'Richard Barone', 'Blues Image']},
"12069":{"count": 25, "artists":['Johnny Thunders_ Patti Palladin', 'Johnny Thunders', 'Johnny Thunder']},
"12071":{"count": 12, "artists":['Rumskib']},
"12073":{"count": 28, "artists":['The Dark Romantics_ ICSU', 'Look Mexico']},
"12083":{"count": 73, "artists":['Jerry Reed']},
"12086":{"count": 132, "artists":['Maps & Atlases', 'Deborah Harry', 'Debbie Harry', 'Alex Harvey Band', 'Andrade', 'The Criminals', 'The Postmarks', 'Glasseater', 'Pretty Ugly']},
"12095":{"count": 50, "artists":['New Mexican Disaster Squad', 'The Pepper Pots', 'Mike Dunn and The Kings Of New England', 'Mike Dunn & The Kings Of New England']},
"12099":{"count": 28, "artists":['Tenth Avenue North']},
"12103":{"count": 63, "artists":['Fred Neil', 'Bertie Higgins']},
"12105":{"count": 253, "artists":['Last Winter', 'God Module', 'The International Submarine Band', 'Gram Parsons', 'The Flying Burrito Brothers', 'Gram Parsons / Emmylou Harris', 'Rick Nelson', 'The Presets', 'Albert Castiglia', 'The Simpletons', 'Dobby Dobson', 'Doddy Dobson', 'Little Atlas', 'Geri X.', 'Alex Martinez', 'Geri X_ Geri X', 'Geri X', 'Nana Mclean', 'Inspector 9', 'Odrareg', 'David Barr', 'Jim Luxon']},
"13021":{"count": 80, "artists":['Little Richard']},
"13059":{"count": 308, "artists":['Leo Kottke;Michael Gordon', 'Leo Kottke', 'Elf Power', 'Modern Skirts', 'Pylon', 'The Gerbils', 'Je Suis France', 'Jet By Day', 'The Maginot Line', 'Summer Hymns', 'Bad Wizard', 'The Bad Wizard', 'Vigilantes Of Love', 'Dark Meat']},
"13067":{"count": 15, "artists":['Lingo']},
"13077":{"count": 64, "artists":['Doug Stone']},
"13081":{"count": 61, "artists":['T Graham Brown', 'T. Graham Brown']},
"13089":{"count": 84, "artists":['Indigo Girls', 'Atlanta Rhythm Section']},
"13115":{"count": 14, "artists":['Butch Walker']},
"13121":{"count": 609, "artists":['Zac Brown Band', 'Black Lips', 'Deerhunter', 'Kristin Hersh', 'Aslyn', 'Snowden', 'The Parties', 'Joe South', 'Young Jules', 'Fight Paris', 'Tommy Roe', 'Georgia Satellites', 'El Pus feat. Tchak Diallo', 'El Pus', 'Confederate Railroad', 'One Way Letter', 'The Heart Attacks', 'Brainbox', 'Kevn Kinney', 'Kelly Hogan', 'The Thorns', 'Scott Wesley Brown', 'Lake Shore Drive', 'Rich Robinson', 'The Forty-Fives', 'Lustre King', 'The Rockingbirds feat. Lesley Rankine', 'The Rockingbirds', 'Faron Young', 'Roy Drusky with Sylvie', 'Roy Drusky', 'Seely', 'Claudio Campadello']},
"13185":{"count": 61, "artists":['Billie Joe Royal', 'Billy Joe Royal', 'Les Humphries Singers']},
"13295":{"count": 48, "artists":['The Forester Sisters']},
"13315":{"count": 11, "artists":['The Cynics', 'Cynics']},
"13319":{"count": 170, "artists":['SubArachnoid Space', 'Steve Harvey', 'Circle Takes the Square', 'The Lost Trailers', 'Big Black', 'Japancakes', 'Gonzalo', 'City of Birmingham Symphony Orchestra/Reginald Kilbey', 'Tony Christie', 'Mad Action', 'Feeder', 'Vox Dei', 'Resistance Dj', 'Resistance', 'Stillwater', 'Taken', 'Chuck Leavell', 'Mad Margritt', 'Left Front Tire', 'Cigar Store Indians', 'King Johnson', 'Jim Lowe', 'Fairburn Royals', 'Small', 'Duke Ellington', '3d5spd', 'Beau Hall', 'Sonset Down']},
"15001":{"count": 114, "artists":['Instrumental', 'Jimpster', 'Edgewater', 'John Legend [feat. Buju Banton]', 'Bitty McLean']},
"16001":{"count": 57, "artists":['Doug Martsch', 'System and Station']},
"16057":{"count": 57, "artists":['Josh Ritter', 'Tony Evans']},
"16059":{"count": 10, "artists":['Pravda', 'Situation Leclerq', 'Scott Riggan']},
"17019":{"count": 153, "artists":['Grupo Los_ Amigos', 'R.E.O. Speedwagon', 'Braid', 'REO Speedwagon', 'The Didjits', 'Journey']},
"17031":{"count": 2065, "artists":['The Smashing Pumpkins and Red Red Meat', 'The Smashing Pumpkins', 'Smashing Pumpkins', 'Wilco', 'Ok Go', 'Daisy s Dead', 'Pelican', 'Barlow Girl', 'Alkaline Trio', 'The Alkaline Trio', 'Hot Water Music', 'The Cartel', 'Cartel', 'Survivor', 'Patti Smith', 'Cafe Tacvba', 'Richard Marx', 'Tortoise', 'Les Trompettes Du Boute Selle', 'Allister', 'Robin Williams', 'Robin Williams & Shelley Duvall', 'The Jesus Lizard', 'Simon Joyner', 'The Sea and Cake', 'John Prine', 'VALENTINE DJ', 'Greens Keepers', 'Greenskeepers', 'Make Believe', 'Vessels', 'The Ponys', 'Peter Cetera with Amy Grant', 'Bountyhunter', 'Office', 'Joan Of Arc', 'Grace Slick', 'Exene Cervenka / John Doe', 'October Fall', 'Jack Nitzsche', 'Jack Nitzche', 'La Kinky Beat', 'The Shadows Of Knight', 'Poison Arrows', 'Ghosts and Vodka', 'John Williamson', 'Jose Ignacio Lapido', 'Blind Ego', 'Dianogah', 'Beaten Awake', 'Articles Of Faith', 'Head of Femur', 'Baby Teeth', 'Tsunami Wazahari', 'Orion', 'Dolium', 'Aliki Vougiouklaki/Lakis Pappas', 'Red Red Meat', 'David Soul', 'Spanky & Our Gang', 'Our Gang', '90 Day Men', 'The Handsome Family', 'Electric Flag', 'The Electric Flag', 'Marc-Andre Fortin', 'The Ides Of March', 'World Stage', 'Ides Of March', 'Paul Butterfield', 'The Paul Butterfield Blues Band', 'Pinetop Seven', 'Troubled Hubble', 'Eleventh Hour', "Cryan' Shames", 'Mason Proffit', 'U.S. Maple', 'Siegel-Schwall', 'The Spinanes', 'We Ragazzi', 'Number One Cup', 'Tommy Sands', 'Tommy Sands and The Raiders', 'The New Colony Six', 'Shrimp Boat', 'Madina Lake', 'John Prine and Mac Wiseman', 'Roger McGuinn', 'The Buckinghams', 'Alice Peacock', 'Comfort Addict', 'Peter Cetera', 'BarlowGirl']},
"17037":{"count": 9, "artists":['Tar']},
"17043":{"count": 120, "artists":['Laurie Anderson', 'Showoff', 'Deviants']},
"17097":{"count": 42, "artists":['The Redwalls', 'The International Submarine Band']},
"17111":{"count": 1, "artists":['The Lemon Drops']},
"17113":{"count": 49, "artists":['Backyard Tire Fire']},
"17119":{"count": 17, "artists":['Bonnie Bramlett', 'Delaney & Bonnie And Friends', 'Delaney & Bonnie & Friends feat. King Curtis', 'Delaney Bonnie & Friends', 'Delaney & Bonnie & Friends']},
"17131":{"count": 52, "artists":['Suzy Bogguss']},
"17143":{"count": 14, "artists":['Minsk']},
"17161":{"count": 31, "artists":['Jude Cole']},
"17167":{"count": 541, "artists":['Mr. Big', 'Oh My God', 'Anni Rossi', 'Tom Fuller Band', 'Fin', 'Lifelike', 'The Days', 'The Steepwater Band', 'Irradio', 'DJ Restless', 'Restless', '56 Hope Road', 'The Assembly', 'Sweet Cobra', 'Drama Queen Die', 'Cracklin Moth', 'Loomis', 'Procession', 'Some Velvet Morning', 'Even In Blackouts', 'Bumpus', 'Joanna Connor', 'Chopin', 'The Honey Bees', 'The Honeybees', 'New Duncan Imperials', 'Tim Kinsella', 'The Great Crusades', 'The Tamlins & Trinity', 'Tamlins', 'The Tamlins', 'Tamlins (feat. Zarro)', 'Little Arthur Duncan', 'Franklin Project', 'The Franklin-Neumann Project', 'Boom', 'Das Gespann', 'Feist']},
"17201":{"count": 18, "artists":['Chris Bathgate', 'The Platters']},
"18005":{"count": 1, "artists":['Gang Green']},
"18021":{"count": 10, "artists":['Henry Lee Summer']},
"18061":{"count": 71, "artists":['Lonnie Mack', 'Stevie Ray Vaughan;Lonnie Mack']},
"18063":{"count": 113, "artists":['Un-Kind', 'Planetary', 'Rapider Than Horsepower', 'Blue News', 'Groupe Vocal de France/John Alldis', 'At War With Self', 'Frank Bradford', 'Revolver', 'Revolver (France)', 'Left Lane Cruiser']},
"18081":{"count": 1, "artists":['Hot Soup']},
"18105":{"count": 170, "artists":['Gianni Dego', 'Murder By Death', 'David Lee Roth', 'Ativin', 'The Panoply Academy']},
"18135":{"count": 22, "artists":['The McCoys']},
"18141":{"count": 17, "artists":['The Rivieras']},
"18163":{"count": 10, "artists":['Amulet']},
"18175":{"count": 1, "artists":['Elephant Micah']},
"19009":{"count": 1, "artists":['C.W. McCall']},
"19017":{"count": 4, "artists":['Postal Blue']},
"19153":{"count": 11, "artists":['Liane Foly', 'To My Surprise']},
"19169":{"count": 169, "artists":['Spoken', 'Joy Electric', 'Roze', 'Jen Gloeckner', 'The Envy Corps', 'Radio Moscow', 'Pieta Brown', 'Tiao Carreiro and Pardinho', 'Splash Candy', 'Rez Band', 'Marcato']},
"20045":{"count": 6, "artists":['The Belles', 'Kill Creek']},
"20047":{"count": 43, "artists":['Freedy Johnston']},
"20125":{"count": 608, "artists":['Stan Ridgway', 'Buckethead / Liu Sola / Nicky Skopelitis / Mick Harris / Jah Wobble', 'Buckethead', 'J Bigga', 'The Ex', 'Puppetmastaz', 'Kingspade', 'Barry Louis Polisar', 'Derek Trucks;Solomon Burke', 'Sarah Bettens', 'Adrenaline', 'Bad English', 'Ross Copperman', 'Crosby / Nash', 'Bonnie Somerville', 'Davy Jones', 'Davy Jones (And The Lower Third)', 'Carl Cartee', 'Little Pieces', 'Jason Knight', 'Poi Dog Pondering', 'Nomadi', 'Boobie Trap', 'While You Were Gone', "The Shakin' Apostles", 'Purple Haze', 'purplehaze', 'Before Braille', 'Vaughan Penn', 'STUART HAMM', 'Stu Hamm', 'Manassas', 'Shebang', "Hard 'n Phirm", 'Hard N Phirm', 'Burning Tree', 'Javier Mendoza Band', 'Mugar', 'Javier Mendoza', 'The Lotus Eaters', 'Jim Ford', 'Silvertone', 'P.Hux', 'P. Hux', 'West_ Bruce & Laing', 'Colorblind James Experience', 'Crosby & Nash', 'REX ALLEN JR.', 'Rex Allen_ Jr.', 'Heart Set Self Destruct']},
"20159":{"count": 38, "artists":['Kerry Livgren']},
"20173":{"count": 26, "artists":['The James Gang', 'Pink Nasty', 'Marvin Rainwater']},
"20177":{"count": 148, "artists":['The Billions', 'Kansas', 'Gerard Lesne/Josep Benet/Josep Cabre']},
"21029":{"count": 38, "artists":['Shadow Dancer', 'Shadowdancer', 'Tupelo Honey', 'John Paul Jones', 'Hilltop Distillery']},
"21037":{"count": 2, "artists":['Swank']},
"21063":{"count": 45, "artists":['Keith Whitley', 'Keith Whitley;Earl Thomas Conley']},
"21067":{"count": 8, "artists":['The Scourge Of The Sea']},
"21081":{"count": 77, "artists":['Skeeter Davis']},
"21083":{"count": 27, "artists":['Sonny Burgess', 'Ray Smith']},
"21095":{"count": 5, "artists":['Rusty York']},
"21111":{"count": 121, "artists":['Joan Osborne', 'Young Widows', 'Georges Guetary', 'PLIHAL KAREL', 'Hunter S. Thompson', 'Artimus Pyle (Lynyrd Skynyrd Alumni)', 'The Sundowners']},
"21115":{"count": 56, "artists":['Crystal Gayle', 'Pam Tillis']},
"21145":{"count": 54, "artists":['Boots Randolph', 'Boots Randolph;The Knightsbridge Strings & Voices', 'Larry Stewart']},
"22017":{"count": 38, "artists":['Victoria Williams']},
"22033":{"count": 22, "artists":['The Roots', 'Chris Thomas', 'Chris Thomas King']},
"22039":{"count": 1, "artists":['Steve Riley & The Mamou Playboys']},
"22051":{"count": 17, "artists":['Joe Clay']},
"22055":{"count": 47, "artists":['Doug Kershaw']},
"22061":{"count": 6, "artists":['Orhistra', 'Jeff Mangum']},
"22071":{"count": 69, "artists":['Kingdom of Sorrow', 'The Subdudes', 'Bobby Mitchell', 'Brent Bourgeois']},
"22073":{"count": 61, "artists":['Dan Deacon', 'Walter Lochmann / Arnold Schoenberg Chor / Ensemble der vereinigten Buhnen Wien / Orchester der Vereinigten Buhnen Wien / Casper Richter', 'Andy Griggs with Guest Vocalist Martina McBride', 'Andy Griggs']},
"22097":{"count": 26, "artists":['Lonnie Brooks']},
"22109":{"count": 43, "artists":['Dax Riggs']},
"22123":{"count": 89, "artists":['Jim Oliver', 'Tony Joe White']},
"22125":{"count": 127, "artists":['HA-ASH;Kalimba', 'HA-ASH', 'Theresa Andersson', 'Imagination Movers', 'Benjy Davis Project', 'Acid Bath', 'Gen Ken Montgomery', 'Broadmoore', 'John Fred And His Playboy Band', 'City Boy', 'Dale And Grace', 'Dale & Grace']},
"23005":{"count": 66, "artists":['Christy Moore', 'Carlo Siliotto', 'Cerberus Shoal', 'Rubato Appassionato']},
"23021":{"count": 51, "artists":['Jim White', 'Pete Kilpatrick', 'PAL', 'Tim Janis', 'Now Is Now']},
"24017":{"count": 26, "artists":['Good Charlotte']},
"24027":{"count": 12, "artists":['Foxy Shazam']},
"24041":{"count": 112, "artists":['The Bakerton Group', 'The Things', 'Montini Trax', 'Lisa Cerbone', 'Bad Apples', 'H.P. Lovecraft', 'Seventh Key', 'Sonus Umbra', 'Live Alien Broadcast', 'Arty Hill and the Long Gone Daddys']},
"24043":{"count": 11, "artists":['Left']},
"24510":{"count": 152, "artists":['Carly Simon', 'Wilderness', 'Greg Kihn', 'PLAY IT', 'Tony Conrad', 'Frank Turner', 'Colton Ford', 'Moss', 'Tony Conrad With Faust', 'The Spades', 'Bob Lind', 'John Hall']},
"25007":{"count": 44, "artists":['Willy Mason']},
"25009":{"count": 51, "artists":['Luke Temple', 'Freddy Cannon', 'Jamie Walters']},
"25015":{"count": 112, "artists":['Stephen Kellogg & The Sixers', 'Erin McKeown', 'J Mascis', 'J Mascis & Friends', 'Four Fifty One']},
"25017":{"count": 201, "artists":['Guster', 'Morphine', 'State Radio', 'Norman Greenbaum', 'Papas Fritas', 'The Vital Might', 'Stelios Bikakis', 'TW Walsh', 'T. W. Walsh']},
"25021":{"count": 73, "artists":['Billy Squier', 'Spirit of the West']},
"25025":{"count": 1171, "artists":['Matt Nathanson', 'Lemonhead', 'The Lemonheads', 'Lemonheads', 'The Click 5', 'The Click Five', 'Mission Of Burma', 'Disciple', 'The Nines', 'The J. Geils Band', 'J. Geils Band', 'Dick Dale & His Del-Tones', 'Dick Dale', 'On Broken Wings', 'Eddie Roberts', 'Craving Lucy', 'Mercyful Fate', 'Jonathan Richman', 'The Modern Lovers', 'Modern Lovers', 'Beautiful Lies', 'Willard Grant Conspiracy', 'Gang Green', 'Mieka Pauley', 'Bob Margolin', 'Cheater Slicks', 'The Other Half', 'Victory At Sea', 'Zurcher Kammerorchester / Howard Griffiths', 'Dons', 'The New Cars', 'El Privates', 'Molemen_ Memo & Longshot', 'Gigolo Aunts', 'Zola', 'Zola;Peter Maffay', 'Bourbon Princess', 'Lyres', 'Alastair Moock', 'The Pandoras', 'Ultimate Spinach', 'Cathal Coughlan', 'Drop Nineteens', 'Earl Gray', 'Twinemen', 'Over The Edge', 'Little Steven', 'Halflife', 'Half Life', 'Capsela', 'Heidi Berry', 'Livingston Taylor', 'Four Piece Suit', 'Aztec Two-Step', 'The Breeders', 'Jon Butcher Axis']},
"25027":{"count": 101, "artists":['Weeping Willows', 'After The Fall', 'Driftwood', 'Mark Mulcahy', 'Cola', 'The Original Sins', 'Fluttr Effect', 'Georgia Gibbs', 'Bronze', 'Drunk Stuntmen', 'Architectural Metaphor']},
"26025":{"count": 1, "artists":['Small Brown Bike_ The Casket Lottery']},
"26031":{"count": 9, "artists":['Sound Barrier']},
"26049":{"count": 125, "artists":['Grand Funk Railroad', 'Grand Funk']},
"26065":{"count": 68, "artists":['Rosetta', 'Auburn Lull', 'Throwing Muses']},
"26073":{"count": 304, "artists":['Anathallo', 'Showdown', 'Discipline', 'Wolf Eyes', 'The Muckrakers', 'The Come Ons', 'Come Ons_ The', 'Looking Up', 'George Lynch', 'Love/Hate', 'Chambers', 'Howling Diablos', 'Inner Soul', 'New Grenada', 'Stewart Francke', 'Medusa Cyclone', 'Sairam', 'Moisture']},
"26081":{"count": 66, "artists":['Whirlwind Heat', 'Brian Vander Ark']},
"26121":{"count": 40, "artists":['Bettye Lavette']},
"26125":{"count": 28, "artists":['Original Capitol Orchestra', 'Kiln', 'No Alternative']},
"26151":{"count": 12, "artists":['Junior Varsity']},
"26161":{"count": 259, "artists":['Iggy Pop_ The Stooges', 'Iggy & The Stooges', 'The Stooges', 'Iggy And The Stooges', 'Marcel Lallemang', 'Midwest Product', 'Jad Fair with Daisy Cooper', 'Jad Fair', 'Brownsville Station', 'Commander Cody', 'Commander Cody & His Lost Planet Airmen', 'Tally Hall', 'Victor Varnado']},
"26163":{"count": 1186, "artists":['The White Stripes', 'The Raconteurs', 'Not Katies', 'Alice Cooper featuring Rob Zombie and Slash', 'The Klone Orchestra', 'Alice Cooper;Jeff Beck With Terry Bozzio And Tony Hymas', 'Alice Cooper featuring Slash', 'Twiztid_ Insane Clown Posse', 'Insane Clown Posse / Perpetual Hype Engine', 'Insane Clown Posse / Russell T. "Old Dirty Bastard" Jones', 'Insane Clown Posse / Mike E Clark', 'Twiztid / Insane Clown Posse', 'Rats', 'Twiztid', 'The Litter', 'The MC5', 'The Romantics', 'Khvost & Vadim Mikhalyuk', 'Louis Corchia', 'Thunderbirds Are Now!', 'Rare Earth', "Bill Haley & Haley's Comets", 'Bill Haley_ The Comets', 'Bill Haley', 'Bill Haley & His Comets', 'Bill Haley And The Comets', 'The Velvelettes', 'The Gories', 'The Hentchmen with Jack White', 'The Hentchmen', 'Dungen', 'Bill Haley and his Comets', 'Kim Weston / Marvin Gaye', 'Frijid Pink', 'Muzikjunki', 'Alice Cooper', 'Destroy All Monsters', 'J. D. SOUTHER', 'J.D. Souther', 'John David Souther', 'Cub Koda', 'Hank Ballard and the Midnighters', 'Hank Ballard', 'Fondas_ The', 'The Fondas', "Dave 'Baby' Cortez", 'Dave "Baby" Cortez', 'Dave Baby Cortez / Dave Cortez', 'Perplexa', '8th Day', 'The 8th Day', '707', 'The Backstreet Girls', 'Freddie Hubbard', 'Giuseppe Mazzoleni', 'Windy And Carl', 'Do Or Die', 'Omnibus Media - Karaoke Tracks', 'The Boy Least Likely To', 'Transient Waves', 'Rev. James Moore', 'Bill Haley & The Comets', 'MC5', 'Suzi Quatro', 'Insane Clown Posse', 'Kim Weston']},
"27001":{"count": 97, "artists":['Drones', 'GB Leighton', 'Pictures of Then', 'Skittish', 'Little Man', 'Martin Devaney', 'Martin Zellar', 'Ingrid Olava']},
"27047":{"count": 46, "artists":['Eddie Cochran & Gene Vincent', 'Eddie Cochran with The Holly Twins', 'Eddie Cochran']},
"27053":{"count": 322, "artists":['The Soviettes', 'The Jayhawks', 'Skhan', 'Cloud Cult', 'Mainstay', 'The Trashmen', 'Now_ Now Every Children', 'The Castaways', 'Mouthful of Bees', 'Lifter Puller', 'Epic Hero', 'Trashmen', 'Spymob', 'The Black Eyed Snakes', 'Jabberwocky', 'Tora! Tora! Torrance', 'Tora! Tora! Torrance!', 'Capital Steps']},
"27123":{"count": 44, "artists":['Grant Hart', 'Hockey Night', 'Ben Weaver']},
"27137":{"count": 24, "artists":['WAIT', 'No Wait Wait']},
"28027":{"count": 4, "artists":['Poney Express', 'Ike & Tina Turner', 'Ike_ Tina Turner']},
"28033":{"count": 67, "artists":['North Mississippi All Stars', 'North Mississippi Allstars', 'The North Mississippi Allstars']},
"28035":{"count": 61, "artists":['Van Dyke Parks']},
"28049":{"count": 30, "artists":['Jonezetta']},
"28057":{"count": 49, "artists":['Jimmy Lunceford', 'Jimmie Lunceford & His Chickasaw Syncopators', 'Jimmie Lunceford And His Orchestra', 'Jimmie Lunceford']},
"28071":{"count": 10, "artists":['Colour Revolt']},
"28075":{"count": 47, "artists":['Steve Forbert', 'Paul Davis', 'Paul Davis / Yvonne Elliman / Annette Brox']},
"28081":{"count": 54, "artists":['Chambers Brothers', 'The Chambers Brothers']},
"28089":{"count": 155, "artists":['Smokie', 'DJ Mog', 'East of Eden', 'Scott McKenzie', 'Cary Hudson', 'Buffalo Nickel Band']},
"28093":{"count": 46, "artists":['Charlie Feathers & His Musical Warriors', 'Charlie Feathers']},
"28107":{"count": 1, "artists":['Laleh']},
"28123":{"count": 10, "artists":['Randy Houser']},
"29069":{"count": 2, "artists":['Onie Wheeler']},
"29077":{"count": 73, "artists":['Someone Still Loves You Boris', 'Someone Still Loves You Boris Yeltsin / Puzzle', 'Someone Still Loves You Boris Yeltsin', 'The Ozark Mountain Daredevils', 'Ozark Mountain Daredevils', 'Ha Ha Tonka']},
"29095":{"count": 87, "artists":['The Feds', 'Feds_ The', 'The Coctails', 'Season To Risk']},
"29131":{"count": 233, "artists":['River Side', 'Riverside', 'Glow', 'Modern Day Zero', "Pavlov's Dog", 'Del', 'DNR Crew Productions', 'Billy Swan with Scotty Moore', 'Billy Swan', 'Billy Swan with Carl Perkins', 'The Incurables', 'Die Symphony', 'Reset', 'Ancient Vision']},
"29135":{"count": 43, "artists":['Gene Clark', 'Dillard & Clark']},
"29145":{"count": 1, "artists":['Steve Gaines / Crawdad']},
"29159":{"count": 20, "artists":['Leroy Van Dyke & Sylvie', 'Leroy Van Dyke']},
"29167":{"count": 11, "artists":['Ronnie Self']},
"29187":{"count": 48, "artists":['Ferlin Husky', 'Ferin Husky']},
"29217":{"count": 4, "artists":['SUE THOMPSON']},
"29510":{"count": 155, "artists":['Living Things', 'So Many Dynamos', 'T-Bone Burnett', 'T Bone Burnett', 'William S. Burroughs / Sonic Youth', 'William S. Burroughs', 'Dazzling Killmen', 'Lightning Slim', 'Eugene Church']},
"30049":{"count": 33, "artists":['Nicolette Larson', 'Nicolette Larson / Michael McDonald']},
"30063":{"count": 62, "artists":['Tarkio', 'Silkworm']},
"30107":{"count": 2, "artists":['Power Yoga Masters', 'Secret Zen Garden']},
"30111":{"count": 9, "artists":['1090 Club']},
"31001":{"count": 28, "artists":['Neal Hefti']},
"31055":{"count": 217, "artists":['Conor Oberst', 'Cursive', 'Desaparecidos', 'Desaparecidos vs Walter Master J', 'Buddy Miles', 'Criteria', 'Curtis Salgado', 'Fee Waybill', 'Fee Waybill_ Steve Lukather_ Tim Bogert_ Tommy Adridg', 'Fizzle Like A Flood']},
"31157":{"count": 13, "artists":['Randy Meisner']},
"32003":{"count": 18, "artists":['Brian Eno And David Byrne', 'Amancio Prada', 'Billy Sherwood', 'Billy Sherwood_ Bret Douglas_ Mike Baker_ Trent Gardner_ Rob LaVaque_ Joh-Hicheal Engard_ Ted Leonard_ Robert Berry', 'Magna-Fi']},
"32023":{"count": 8, "artists":['Slow To Surface']},
"33007":{"count": 96, "artists":['GG Allin']},
"33009":{"count": 2, "artists":['Bill Morrissey']},
"33015":{"count": 12, "artists":['Rookie']},
"34001":{"count": 3, "artists":['Edsel']},
"34003":{"count": 3, "artists":['The Knickerbockers']},
"34005":{"count": 707, "artists":['The Temper Trap', 'Midtown', 'Chris Garneau', 'Bigwig', 'Dr. Hook', 'Gary Wright', 'Gary Wright with Dorian Wright', 'Laleh', 'Fully Loaded', 'Street Ministry', 'Fully Loaded featuring DJ Nitro', 'Antigone Rising', 'Electric Frankenstein', 'Magnatune Compilation', 'New London Fire', 'Johanna Stahley', 'Steven Delopoulos', 'The Wrens', 'All Parallels', 'Solid Pr Presents', 'St. Christopher', 'Osanna', 'Massimo', 'Sally & Vip-R', 'Sally', 'All Natural Lemon And Lime Flavors', 'All Natural Lemon & Lime Flavors', 'Cassius Clay', 'Stacie Rose', 'The Re-Mains', 'R. Stevie Moore', 'Mucky Pup', 'Roots of Rebellion', 'Frankenstein 3000', 'Tara Angell', 'Murder 1', 'Those Dreaded Gnats', 'Lonnie Youngblood', 'Gene Walk Group', 'Jane Kelly Williams', 'Mothers Little Helpers', 'Pugh', 'Let It Burn']},
"34009":{"count": 97, "artists":['Freebo', 'Mick Chillage', 'Walter Trout']},
"34013":{"count": 41, "artists":['Jerry Lewis']},
"34017":{"count": 143, "artists":['Kurt Widmann & Sein Orchester', 'Yo La Tengo', 'Husum', 'Black Label Society', 'Zakk Wylde', 'Adi Smolar', 'The Feelies']},
"34021":{"count": 47, "artists":['Mary Chapin Carpenter']},
"34023":{"count": 92, "artists":['Jeff Larson', 'Nina Kinert', 'The Smithereens']},
"34025":{"count": 140, "artists":['Giuseppe Ielasi', 'Bruce Springsteen & The E Street Band', 'Bruce Springsteen', 'Val Emmich', 'Juanita Hall', 'Bloody Mary & The Ken Darby Singers', 'Miyoshi Umeki;Larry Blyden;Juanita Hall;Ed Kenney;Keye Luke', 'Miyoshi Umeki & Broadway Cast']},
"34027":{"count": 34, "artists":['Neal Casal']},
"34031":{"count": 158, "artists":['Donald Fagen', 'EAST ASIA  Japan: Geza Music from the Kabuki', 'Dramarama', 'Whiplash', 'The Happenings']},
"34035":{"count": 9, "artists":['Second Left']},
"34037":{"count": 28, "artists":['Moneyshot']},
"34039":{"count": 18, "artists":['Doughboys']},
"35001":{"count": 72, "artists":['A Hawk And A Hacksaw', 'Scared Of Chaka']},
"35007":{"count": 47, "artists":['The Fireballs featuring Chuck Tharp', 'The Fireballs', 'The Fireballs Feat. Jimmy Gilmer']},
"35045":{"count": 1, "artists":['Teengenerate']},
"35053":{"count": 73, "artists":['Simple / Raw-B / Fabster', 'Simple', 'Simple / Spit', "Sky / Lil' Dank / Young Lee", 'Sky', 'The Knights', 'Sticky Pistil']},
"36005":{"count": 156, "artists":['The Blues Magoos', 'Popa Chubby', 'Joe White', 'Slim Smith & Friends', 'Fly Ashtray', 'Ernie Maresca', 'Laura Nyro', 'Laura Nyro;LaBelle']},
"36015":{"count": 12, "artists":['Elkland']},
"36027":{"count": 23, "artists":['Samson Francois', 'Stratos Dionysiou', 'Hopewell']},
"36029":{"count": 190, "artists":['Brian McKnight / Fabolous / Six John', 'Brian McKnight / Nelly', 'Brian McKnight / Mr.Cheeks / Baby', 'Brian McKnight / Juvenile / Akon / Skip', 'Brian McKnight_ Mya_ Nate Dogg_ Sonny (P.O.D.)_ Jacoby (Papa Roach)_ FeFe Dobson_ Pete (Chevelle)_ Ben Jelen_ Ben Moody_ others', 'Brian McKnight / Talib Kweli', 'Brian McKnight / Kirk Franklin', 'Brian McKnight / Mase', 'Brian McKnight', 'Ani DiFranco', 'Vincent Gallo', 'Strife/Tony Victory', 'Strife', 'Snapcase', 'Lucky Peterson', 'Baseball Furies']},
"36033":{"count": 37, "artists":['Bob Mould']},
"36037":{"count": 3, "artists":['Down-To-Earth Approach', 'Down To Earth Approach']},
"36047":{"count": 1252, "artists":['Lou Reed', 'Lou Reed (Featuring Antony)', 'Lou Reed (Featuring Ornette Coleman)', 'Pat Benatar', 'Clap Your Hands Say Yeah', 'Harry Nilsson;George Tipton', 'Harry Nilsson;Ken  Ascher', 'Harry Nilsson', 'Eddie Money', 'Ronn Matlock', 'Eddie Money with Ronnie Spector', 'The Ultimate Beatles Cover Band', 'Department of Eagles', 'Joan As Police Woman', 'Joan As Police Woman feat. Rufus Wainwright', 'Arlo Guthrie', 'Longwave/Nanchang Nancy', 'Santos Inocentes', 'CALLA', 'Otto Klemperer', 'Storybox', 'Japanther', 'The Cloud Room', 'Meneguar', 'Richie Havens', 'Gregg Burge', 'Lymbyc Systym', 'Parts & Labor', 'White Magic', 'Metallic Falcons', 'The Jealous Girlfriends', 'Oxford Collapse', 'Eddie Rabbitt', 'Post War Years', 'The Forms', 'The World/Inferno Friendship Society', 'World Inferno Friendship Society', 'World Inferno/Friendship Society_ The', 'World / Inferno Friendship Society', 'Mixel Pixel (with Lauren Winslow)', 'Antonio Koudele', 'Mixel Pixel', 'The Rogers Sisters', 'The Rogers', 'Ready Fire Aim', 'Oakley Hall', 'The Parties', 'Les Sans Culottes', 'Night Dreamers', 'UM Dancekings', 'The Up And Downs', 'Al Kooper;Mike Bloomfield;Stephen Stills', 'Al Kooper', 'Al Kooper;Shuggie Otis', 'Al Kooper;Steve Stills', 'TK Webb_ The Visions', 'Garland Jeffreys', 'Garland Jeffreys / Joe Dworniak', 'Robbie Dupree', 'Peter Criss', 'The Strangeloves', 'Al Kooper;Mike Bloomfield', 'Hermit Thrushes', 'Henry Gross', 'Maewest', 'Mae West', 'Thirstin Howl III', 'Rack-Lo', 'Elliot Easton', 'AM Radio', 'All About Chad', 'Longwave']},
"36055":{"count": 110, "artists":['Tony Levin_ Paul Dunmall', 'Tony Levin', 'Lou Gramm', 'Michael Bolton;The Philharmonia Orchestra;Steven Mercurio', 'SNMNMNM', 'Jess Klein', 'Ersel Hickey', 'Kid Lunch']},
"36059":{"count": 116, "artists":['David Mead', 'The Routers', 'Audra McDonald']},
"36061":{"count": 4811, "artists":['Choeur Armenien de Sofia', 'Alex Torn', 'The Bravery', 'Interpol', 'The Strokes', 'Rasputina', 'Amo_ neoklash_ noobles', 'David Liebe Hart & Adam Papagan and Power Animal', 'AMO', 'Idina Menzel', 'Huggotron', 'Idina Menzel / Leo Norbert Butz', 'Maria Solheim', 'Foreigner', 'Pete Seeger with Memphis Slim and Willie Dixon', 'Pete Seeger', 'Ro', "Lovin' Spoonful", 'The Brand New Heavies', 'The Humpers', 'New Bomb Turks', 'Discipline', 'Nightmare Of You', 'The Young Rascals', 'The Slackers', 'Peter_ Paul and Mary', 'Noel Paul Stookey', 'Peter Yarrow', 'Peter_ Paul & Mary', 'David Byrne', 'David Byrne & Brian Eno', 'John Lurie', 'La Casa', 'Danny Hoch', 'Soul Coughing', 'Geggy Tah', "Terence Trent D'Arby;Booker T & The MG's", "Terence Trent D'Arby Duet with Des'ree", "Terence Trent D'Arby", 'Ram Jam', 'Jay Brannan', 'Ryan Star', 'Tom Aragon', 'Ivy', 'Cymbals Eat Guitars', 'The Ark', 'Stephen Lynch', 'Stretch Arm Strong', 'Cast', 'Dawn Landes', 'The Damnwells', 'Reagan Youth', 'Book Of Love', 'Dana Fuchs', 'Frustration', 'Michael McDonald', 'Aaron Zimmer', 'Dive', 'Dive_ Diskonnekted', 'Dive Vs. Diskonnekted', 'Deville_ Willy', 'Willy De Ville', 'Natural History feat. Joe Morris', 'Natural History', 'The Natural History', 'Winger', 'Kelley Stoltz', 'Status Quo', 'Growing', 'Groovemaster G', 'Blood_ Sweat & Tears', 'Young Lords_ Kites_ Prurient', 'The Fevers', 'Excepter', 'The Belt', 'Belt', 'Chavez', 'Lucy Woodward', 'Montefiori Cocktail featuring Scanna', 'Indian Bottom Association Old Regular Baptists / Elliot Goldenthal', 'Elliot Goldenthal', 'The Lost Patrol', 'King Missile', 'Andre Mehmari', 'Eric Bibb', 'ZO2', 'Blue Girl', 'Black Tape For A Blue Girl', 'Psychic Ills', 'Meredith Monk', 'Meredith Monk_ Katie Geissinger', 'Meredith Monk and Vocal Ensemble', 'Meredith Monk_ Theo Bleckmann_ Ellen Fisher_ Katie Geissinger_ Ching Gonzalez_ Allison Sniffin_ Sash', 'The Beat Poets', 'Sightings', 'A.R.E. Weapons', 'Orleans', 'JBM', 'Amplify', 'Lucy Wainwright Roche', 'The Daysleepers', 'DaySleepers', 'Rivermaya', 'Aarktica with Aaron Spectre', 'Aarktica', 'Pete Francis', 'Lucy Kaplansky', 'Assembly of Dust', 'Hawk Eye', 'Hawkeye', 'Jeff Finlin', 'Phoebe Snow', 'Bloody Social', "J'ai toujours reve d'etre un gangster", 'Vanilla Fudge', 'Steven Tyler;Emily Watson', 'Steven Tyler;Henry Stram;Tim Jerome', 'Steven Tyler;Henry Stram;Tim Jerome;Vicki Clark;Erin Hill;Dan Jenkins;Chris McKinney', 'Steven Tyler;Polly Jean Harvey;Rob Ellis', 'Steven Tyler;Eddie Vedder;Susan Sarandon', 'Steven Tyler', 'Looker', 'The Churchills', 'Dan Zanes Feat. Cynthia Hopkins', 'Dan Zanes Feat. Donald Saaf and The Rocket Ship Singers', 'Dan Zanes Feat. Aimee Mann', 'Dan Zanes Feat. Angelique Kidjo', "Dan Zanes Feat. Rankin' Don And The Rocket Ship Singers", 'Dan Zanes Feat. John Doe', 'Dan Zanes Feat. Lou Reed And The Rubi Theater Company', 'Dan Zanes Feat. Philip Glass', 'Dan Zanes Feat. Aggie Decaul And Courin Gibbs', 'Dan Zanes Feat. Sheryl Crow', 'Dan Zanes', 'Dan Zanes Feat. Bob Weir', 'Dan Zanes Feat. A Cast Of Thousands!!', 'Dan Zanes Feat. The Sandy Girls', 'Dan Zanes Feat. Suzanne Vega', 'Dan Zanes Feat. Dar Williams', "Dan Zanes Feat. Rankin' Don aka Father Goose", 'Dan Zanes Feat. Yoshi Waki', 'Emii', 'James Chance | The Contortions', 'James Chance & the Contortions', 'Joe Piket', 'This Island Earth', 'The Bloodsugars', 'Pearls Before Swine', 'Miss Kenichi', 'Man on Earth', 'Jay & The Americans', 'Mink DeVille', 'The Waves', 'Matthew Wilder', 'Jimmy Durante', 'Art Ensemble Of Chicago', 'Greg Lake', 'KaiserCartel', 'Kaiser Cartel', 'The Book Of Knots', 'The Silos', 'Kitty & the Kowalskis', 'Leslie West', 'Pinstripes', 'Arjun', 'Patent Pending', 'The Fugs', 'Vain', 'Holy Modal Rounders', "Li'l Cap'n Travis", 'Lansing-Dreiden', 'Paxton', 'The Shake', 'David Gilmour', 'Unto Ashes', 'The Story', 'Doug Wimbish', 'Doug Wimbish feat. Adrian Sherwood', 'Doug Wimbish feat. Bernard Fowler', 'Doug Wimbish feat. Shara Nelson', 'HeadQuarters', 'JJ Appleton', 'cholo', 'Dan Melchior', "The Whitest Kids U' Know", 'Chip Taylor_ Evie Sands', 'Chip Taylor_ Carrie Rodriguez', 'Chip Taylor', 'Steven Mark', 'Walter Becker', 'Jana Kirschner', 'The Strings Of Paris', 'Synaesthesia', 'Metropolis', 'Synsthesia', 'El Vira', 'Elvira_ Zulima_ Mustafa_ Haly_ Coro_ Staatskapelle Dresden und der Chor der Staatsoper Dresden', 'Elvira', 'Mary Hall Surface & David Maddox', 'The Unsacred Hearts', 'Patti Rothberg', 'Al Duvall', 'Kate Wolf', 'Kate Wolf & The Wildwood Flower', 'Soundscape', 'Corale Polifonica Jubilate Deo', '1 Mile North', 'Kites', 'Nora Dean', 'The Poise Rite', 'Gary Portnoy', 'Dictators', 'Casey Shea', 'Distractions', 'God Is My Co-Pilot', 'Sim Redmond Band', 'G.G. Allin', 'Jim Steinman', "Pandora's Box", 'Roberto Prosseda', '3kStatic', 'Grain', 'Velcro Stars', 'Sugar Eater', 'Eddie Ojeda', 'Swiss Auto Club', 'Greener', 'Johnny Ray', 'Steve Lee', 'Aerovox', 'The Lizards', 'Greatdayforup', 'Project Skyward', 'The Hollies', 'Ambelique', 'Valeze', 'Sandy Bull', 'Darren Styles', 'Tuff Darts', 'Annie Minogue Band', 'The Blues Project', 'Garrison', 'The Reach', 'Stierkampf', 'The Friggs', 'Jolene', 'Burnout', 'Dave Derby', 'Dave Derby & The Norfolk Downs', 'Helios Creed', 'Jeremy Kushnier', 'Jenny Martin', 'The Chrome Cranks', 'Chrome Cranks', 'Speedball Baby', "Pancho's Lament", 'Delta Goodrem', 'Paul Evans', 'theFringe', 'The Jason Bonham Band', 'Pawnshop', 'Wooden Wand And The Vanishing Voice', 'Patric La Funk & Jorgensen', 'Bob Smith', 'Dan Zanes Feat. The Rocket Ship Revue', 'Dan Zanes Feat. Barbara Brousal', 'Prewar Yardsale', 'Pat Farrell & Meltdown', 'Pat Farrell feat. MC Eve', 'Pat Farrell', 'Glampire', 'P.F. Sloan', 'The Gryphon Trio', 'Shy Child', 'The Minors', 'Debbie Friedman', 'Ultra Vivid Scene', 'Poem Rocket', 'Jose Luis Duval', 'Unbelievable!', 'Willy DeVille', 'Ismael Serrano', 'Bob Evans', 'applied communications', 'Jana Kirschner / M. Zbirka', 'Bang on a Can All-Stars', 'Spin Doctors', 'Swim Two Birds', 'Frogg Cafe', 'Anne Regina', 'Alan Silvestri', 'Foghat', 'Edd Byrnes', 'Suicide', 'Blanc Faces', 'Harry Chapin', 'Say Hi To Your Mom', 'The Mooney Suzuki', 'Alexander Vaulin', 'John Berenzy', 'The Gun & Doll Show', 'Pat Farrell featuring Patrick Miller', 'Jones Crusher', 'Manfred Trendel', 'Carmin Turco', "The Lovin' Spoonful", 'Nell Bryden', 'Orange Blue', 'Bette Midler (Duet with Linda Ronstadt)', 'Studio Sound Group', 'Edwin McCain', 'Lee Roy Parnell', 'The Inchtabokatables', 'Victims / From Ashes Rise']},
"36065":{"count": 11, "artists":['Annette Funicello']},
"36067":{"count": 14, "artists":['Bobcat Goldthwait']},
"36071":{"count": 99, "artists":['The Morning Of', 'Bill Perry & Richie Havens', 'Bill Perry', 'Joey Heatherton']},
"36081":{"count": 216, "artists":['Art Garfunkel and Amy Grant', 'Art Garfunkel; Strings and horns arranged and conducted by Del Newman', 'Furthest From the Star', 'Jack Johnson', 'Paul Stanley', 'Fleshtones feat. Alan Vega', 'Fleshtones', 'The Fleshtones', 'Bernadette Peters/2003 Broadway Cast "Gypsy', 'Bernadette Peters;John Mauceri', 'Bernadette Peters;Paul Gemignani', 'Bernadette Peters', 'Bernadette Peters/Annie Get Your Gun - 1999 Broadway Cast', 'Walter Egan', 'Kieran Kane', 'Art Garfunkel', 'Eine Kleine Nacht Musik']},
"36085":{"count": 213, "artists":['Joan Baez_ Mary Chapin Carpenter', 'Joan Baez_ Kate McGarrigle_ Anna Mc Garrigle', 'Blue Sky Boys', 'Joan Baez / Joni Mitchell', 'David Johansen', 'Joan Baez', 'The Cuff Links']},
"36099":{"count": 107, "artists":['Enigma', 'The Sun Shiners']},
"36101":{"count": 43, "artists":['Duane Eddy', 'Duanne Eddy', 'Eddy Duane']},
"36103":{"count": 252, "artists":['Leonard Cohen', 'Leonard Cohen / U2', 'As Tall As Lions', 'Mountain', 'Mountain;Leslie West', 'Lee Rocker', 'The Reunion Show', 'Reunion Show', 'Terry Winchell']},
"36111":{"count": 10, "artists":['David Navarro', 'Dave Navarro']},
"36119":{"count": 175, "artists":['The Moldy Peaches', 'Don McLean', 'Pop Noir', 'Refuge', 'Felix Cavaliere']},
"37013":{"count": 18, "artists":['Guitar Shorty']},
"37063":{"count": 77, "artists":['Betty Davis', 'John D. Loudermilk']},
"37067":{"count": 17, "artists":['TIMO TOLKKI']},
"37075":{"count": 95, "artists":['MILSAP_ RONNIE', 'Ronnie Milsap']},
"37081":{"count": 14, "artists":['Absynthe Minded', 'Tremors']},
"37085":{"count": 48, "artists":['The Ponies', 'Charles Aznavour', 'Link Wray']},
"37119":{"count": 39, "artists":['K-Ci & JoJo']},
"37123":{"count": 157, "artists":['Clifton', 'Hotel Lights', 'Fist', 'Little Eva', 'The Royal We', 'Delicious feat. Tiger Lily', 'Delicious', 'Madia', 'Copperhead', 'Barrington Levy', 'De Lorean', 'De Lorean feat. Eylem', 'Hadeeqa Kiyani', 'Jr. James & the Late Guitar', 'JennyAnyKind', 'The Raleigh Ringers']},
"37129":{"count": 44, "artists":['He Is Legend']},
"37135":{"count": 190, "artists":['Polvo', 'Loudon Wainwright III (Lucy Wainwright Roche)', 'Superchunk', 'John Kirkpatrick', 'The Out Crowd', 'The Outcrowd', 'Schooner', 'Loudon Wainwright III', 'Arrogance', 'Delorean']},
"37147":{"count": 54, "artists":['Ana Maria Martinez - Ignacio Rodes', 'The Avett Brothers']},
"37183":{"count": 129, "artists":['Whiskeytown', 'Steve Cropper & Felix Cavaliere', 'Steve Cropper / Pop Staples / Albert King', 'Steve Cropper', 'Dog Faced Gods']},
"37193":{"count": 21, "artists":['OLIVER', 'Oliver Dodd']},
"38017":{"count": 12, "artists":['Shannon Curfman', 'Shannon Curfman & Joe Bonamassa']},
"38035":{"count": 72, "artists":['Lynn Anderson', 'Tom Brosseau', 'Frank Ifield']},
"39017":{"count": 58, "artists":['The Afghan Whigs', 'Afghan Whigs']},
"39021":{"count": 28, "artists":['Superchick Featuring ThumpMonks', 'Superchic(k)', 'Superchick']},
"39025":{"count": 75, "artists":['Mott The Hoople']},
"39027":{"count": 1, "artists":['Gran Bel Fisher']},
"39035":{"count": 482, "artists":['Bravo Romeo Bravo', 'Tracy Chapman', 'Tracy Chapman / Luciano Pavarotti / Orchestra Sinfonica Italiana / Jose Molina', 'Paris Yard', 'Eric Carmen', 'Pere Ubu', 'Benny Mardones featuring Teresa James', 'Benny Mardones', 'David Coverdale', 'The James Gang', 'James Gang', 'Joachim Pfahl', 'Freddie Brocksieper', 'This Moment In Black History', 'This Moment', 'Don Nix', 'My Dad Is Dead', 'The Dreadful Yawns', 'The Vacancies', 'John Popper', 'Rocket From The Tombs', 'Cisse Hakkinen', 'Michael Stanley', 'Michael Stanley Band', 'Weber-Beckmann plus', 'Ten', 'Prisonshake', 'The Alarm Clocks']},
"39049":{"count": 149, "artists":['Two Cow Garage', 'McGuffey Lane', 'Bassholes', 'The Whiles', "The Rockin' Bandits", 'The Gibson Bros.', 'The Yips']},
"39057":{"count": 45, "artists":['Richie Furay', 'The Richie Furay Band', 'Furay_ Richie Band']},
"39061":{"count": 203, "artists":['Starfield', 'Over The Rhine', 'Freekbass', 'Lemon Pipers', 'The Lemon Pipers', 'Marty Balin', 'Ass Ponys', 'Blessid Union Of Souls']},
"39071":{"count": 1, "artists":['Johnny Paycheck']},
"39089":{"count": 433, "artists":['Lovedrug', 'Scott Walker', 'Luciano Varnadi Ceriello', 'Goose', 'Fabiano Bion', 'Oracle', 'Hardfloor', 'Hierophant', 'Malice In Wonderland', 'Wendy James', 'Milestone', 'Joe Vitale', 'EMBASSY', 'Jackpot', 'View From Everest', 'Chalk', 'Intell', 'Big Money', 'Coffinberry', 'Byron Nemeth', 'Quarkspace', 'Clouds Forming Crowns', 'Nine Days Wonder', "Len's Lounge", 'Them Wranch', 'Greenhorn', 'Dallas Moore', 'Wheels On Fire']},
"39093":{"count": 59, "artists":['Los Enemigos']},
"39095":{"count": 2, "artists":['Jessica Bailiff']},
"39107":{"count": 60, "artists":['Rick Derringer']},
"39113":{"count": 86, "artists":['Tommy James And The Shondells', 'Brainiac', 'Lou Barlow', 'Tim Hagans', 'Swearing At Motorists']},
"39133":{"count": 12, "artists":['Beaten Awake', 'Bernhard Brink']},
"39139":{"count": 35, "artists":['Ohio Express feat. RocknRoll Orchester', 'Ohio Express', 'Estudio Miami Ritmo']},
"39145":{"count": 13, "artists":['Ras Flabba', 'Earl Thomas Conley']},
"39151":{"count": 47, "artists":['Boz Skaggs', 'Boz Scaggs']},
"39153":{"count": 133, "artists":['The Black Keys', 'Rachel Sweet']},
"39167":{"count": 39, "artists":['Dee Dee Sharp Gamble', 'Dee Dee Sharp']},
"40015":{"count": 74, "artists":['subseven', 'Gin', 'Jami Smith', 'Maria-Joao Pires', 'SRC', 'Jesse Ed Davis', 'Jesse Davis', 'G.I.N.', 'G.I.N._ Lady Assassin', 'G.I.N._ Lyrical 187_ Big Pokey_ Mr. Got Damn']},
"40023":{"count": 15, "artists":['Ray Wylie Hubbard']},
"40031":{"count": 85, "artists":['Leon Russell & New Grass Revival', 'Leon Russell', 'Leon Russel']},
"40037":{"count": 2, "artists":['Lee Hazlewood']},
"40057":{"count": 16, "artists":['Terry Stafford', 'Glenn Barber']},
"40097":{"count": 23, "artists":['Carl Belew']},
"40109":{"count": 183, "artists":['J. J. Cale & Eric Clapton', 'J.J. Cale & Eric Clapton', 'J.J. Cale', 'Barry McGuire', 'Barry McGuire & Friends', 'Tommy Overstreet', 'Radial Spangle']},
"40115":{"count": 37, "artists":['Ace Moreland']},
"40119":{"count": 1, "artists":['James Talley']},
"40123":{"count": 59, "artists":['Blake Shelton']},
"40125":{"count": 93, "artists":['Wanda Jackson with Mike Post', 'Wanda Jackson']},
"40137":{"count": 47, "artists":['Hoyt Axton']},
"40143":{"count": 113, "artists":['A&M', 'Joe Diffie', 'Joe Diffie / Lee Ann Womack', 'The Tractors', 'Sanford Clark', 'AM']},
"41005":{"count": 25, "artists":['Meredith Brooks', 'Dead Moon']},
"41013":{"count": 358, "artists":['Hockey', 'Invisible', 'Richmond Fontaine', 'Norman And Nancy Blakie', 'Norman', "Norman & Nancy Blake_ Tim O'Brian", 'Norman - Spencer - Galimi - Lepage', 'Penta', 'M', 'Susan James', 'Reverend And The Makers', 'Weinland', 'Michael Hurley', 'Point Juncture_ WA', 'Point Juncture WA', 'Mickey Newbury', 'Scott Huckabay', 'Railer', 'Higher Ground', 'Jeff Trott', 'Lewi Longmire_ Bingo (Kevin Richey)_ Ned Folkerth_ Bill Rudolph', 'David Jacobs-Strain', 'Roedelius / Lunz', 'Alan Singley', 'Sweet Juice', 'Sarah Dougher']},
"41039":{"count": 118, "artists":["Cherry Poppin' Daddies", 'Tim Hardin', 'Mark Lindsay', 'Cadet']},
"41047":{"count": 39, "artists":['Joaquin Phoenix/Reese Witherspoon', 'Joaquin Phoenix', 'Dolorean']},
"41051":{"count": 344, "artists":['The Kingsmen', 'Sohodolls', 'Horse Feathers', 'Kaddisfly', 'Above The Golden State', '31Knots', 'Heatmiser', 'Jeff London', 'Kind of Like Spitting', 'Talkdemonic', 'Jorma Kaukonen & Tom Constanten', 'Ever We Fall', 'Wet Confetti', 'DOC Nasty vs. Supernaut', 'Supernaut vs. D.O.C. Nasty', 'Please Step Out Of The Vehicle', 'Pell Mell', 'Point Line Plane', 'Thanksgiving', '31 Knots']},
"41053":{"count": 87, "artists":['Johnnie Ray;The Buddy Cole Quartet', 'Johnnie Ray with the four lads', 'Johnnie Ray;Ray Conniff', 'Johnnie Ray & Doris Day', 'Johnny Ray', 'Johnnie Ray']},
"42003":{"count": 108, "artists":['The Schoolgirls', 'Don Caballero', 'Modey Lemon', 'Jimmy Thackery And The Drivers', 'T.Rex', 'Jimmy Thackery', 'We Should Be Dead', 'Hurl']},
"42011":{"count": 17, "artists":['The Jazz June']},
"42017":{"count": 94, "artists":['Ween']},
"42027":{"count": 412, "artists":['Slade', 'The Badlees', 'Rising Sun', 'Poptart Monkeys', 'Pumice', 'The Brakes', 'Amy Rigby', 'Total Fucking Destruction', 'Rusted Shut', 'East Hundred', 'HOSTILE TAKEOVER', 'Portico', 'overlord', 'Swoon', 'Monkeywrench', 'DJ Devious', 'Annie Haslam', 'DeSoto Rust', 'John Foxx & Louis Gordon', 'Punchdrunk', 'Kyf Brewer', 'Steve Guyger', 'Backstreet Law', 'Woody Whatever', 'Free For All', 'Tom Shaw', 'Jefferson Pepper', 'Belinda Carlisle', 'Vehicle Flips', 'Billy Price_ Fred Chapellier']},
"42043":{"count": 11, "artists":['We Are Balboa']},
"42045":{"count": 5, "artists":['Azusa Plane']},
"42077":{"count": 1, "artists":['John Mayall']},
"42079":{"count": 56, "artists":['An Albatross']},
"42091":{"count": 13, "artists":['Jobriath']},
"42095":{"count": 19, "artists":['The Cyrkle']},
"42101":{"count": 695, "artists":['G. Love & Special Sauce', 'Man Man', 'A Life Once Lost', 'Joan Jett and the Blackhearts', 'Joan Jett & The Blackhearts', 'Zolof The Rock & Roll Destroyer', 'Days Away', 'The Dead Milkmen', 'Saturday Evening Post', 'Chubby Checker', 'The River Bends', 'Denison Witmer', 'Michael Sembello', 'Zolof The Rock and Roll Destroyer', 'Pattern is Movement', 'Bardo Pond', 'Altar', 'Lilys', 'Mord', 'Scuba', 'Sixieme Sens', 'Frankie Avalon', 'Nazz', 'The Bacon Brothers', 'Bobby Rydell', 'Bobby Rydell / Chubby Checker', 'National Eye', 'Charlie Gracie', 'The Bigger Lovers', 'Len Barry', 'SENSATIONS_ The', 'Sensations', 'Hash Jar Tempo', 'Charlie Gracie & The Wildcats']},
"42133":{"count": 77, "artists":['Live', 'Live / Shelby Lynne']},
"44003":{"count": 122, "artists":['The Chinese Stars', 'Mindflayer', 'Six Finger Satellite', 'Les Dudek', 'C.S. Radhakrishna', 'Alec K. Redfearn and The Eyesores']},
"44005":{"count": 39, "artists":['Tanya Donelly_ Dylan In The Movies', 'Tanya Donelly', 'Susan Cowsill']},
"44007":{"count": 34, "artists":['Zox', 'David Blue', 'Landed']},
"45003":{"count": 73, "artists":['Faulconer_ Bruce', 'John Berry']},
"45019":{"count": 64, "artists":['GROVER WASHINGTON_ JR.', 'Sign of the Times', 'Band Of Horses', 'NEEDTOBREATHE']},
"45035":{"count": 2, "artists":['Maria Callas/Coro del Teatro alla Scala_ Milano/Noberto Mola/Orchestra del Teatro alla Scala_ Milano/Gianandrea Gavazzeni', 'The Roots of Orchis']},
"45075":{"count": 111, "artists":['M.I.', 'Pur', 'Jay Clifford', 'Object', 'Runrig', 'John Amen', 'From Safety To Where']},
"45079":{"count": 11, "artists":['Silers Bald']},
"45083":{"count": 1, "artists":['The Marshall Tucker Band']},
"46027":{"count": 91, "artists":['Shawn Colvin']},
"47015":{"count": 684, "artists":['Jeff Buckley featuring Alim Qasimov', 'Jeff Buckley', 'Sara Evans & Bethany Olds', 'Sara Evans', 'Old Crow Medicine Show', 'Katie Herzig', 'Copper', "Lanae' Hale", 'Jaime Jamgochian', 'Ulabrand', 'Jonah33', 'Madi Diaz', 'The Young Republic', 'Everly Brothers', 'Kate York', 'Royal Bangs', 'Jeni Varnadeau', 'Flatline feat. Darker Knight', '54 Seconds', 'Juan Prophet Organization', 'Cub', 'Scott Holt', 'The Mattoid', 'The Burn', 'Susan Marshall', 'Marshall_ Susan', 'Sarah Siskind', 'Andrew Osenga', 'Mike Younger', 'Cindy Bullens', 'Oblio', 'Polecat Boogie Revival', 'Hour Glass Men', 'Drifting in Silence', 'The Bo-Keys featuring Harvey Scales', 'The Bo-Keys', 'The Bo Keys', 'Area Code', 'Bob Cheevers', 'Smokehouse', 'Salem Hill', 'Adam Ant', 'Don King', 'Sid Selvidge', "Bill Black's Combo", 'Garr Lange', 'Tydyl Wave', 'Don Nix', 'Marthia Sides', 'Cindy Bullens / Louis St. Louis', 'Harlan T. Bobo', 'Mario DaSilva']},
"47035":{"count": 17, "artists":['Bill Parsons (aka Bobby Bare)', 'Bill Parsons']},
"47037":{"count": 665, "artists":['Kings Of Leon', 'Nicolette Larson', 'Laura Cantrell', 'Griffin House', 'Tavares', 'Nikolaus Harnoncourt & Concentus musicus Wien', 'Lambchop', 'Kip Winger', 'Me In Motion', 'Brooke Waggoner', 'Zuchthausrap feat. Mc Andeejay feat. Blerta & G.Capella', 'Today Is The Day', 'Los Straitjackets', 'De Novo Dahl', 'Carlene Carter', 'Carlene Carter and Ronnie Dunn', 'Gregg Allman', 'Forget Cassettes', 'Duane Allman', 'Johnny Jenkins / Duane Allman', 'Duane Allman / Derek & The Dominos', 'King Curtis / Duane Allman', 'Duane Allman / Delaney Bonnie & Friends', 'Barrence Whitfield', 'The Karaoke Channel', 'Ellen McIlwaine', 'Doug Hoekstra', 'Jimmy Norman', 'Lume', 'Secret Zen Garden', 'Bobby Russell', 'Warner mack']},
"47053":{"count": 50, "artists":['T.G.Sheppard', 'T.G. Sheppard']},
"47065":{"count": 39, "artists":['Derek Martin', 'Derek Martin_ Hans Edler']},
"47071":{"count": 49, "artists":['Ski-King', 'Lindisfarne']},
"47075":{"count": 99, "artists":['Tina Turner', 'Tina Turner Featuring Lisa Fischer']},
"47079":{"count": 4, "artists":['Merle Kilgore']},
"47091":{"count": 10, "artists":['Dave Loggins']},
"47113":{"count": 1, "artists":['Big Maybelle']},
"47149":{"count": 39, "artists":['The Boomers']},
"47157":{"count": 283, "artists":['Skillet', 'Johnny Burnette & The Rock \x18N\x19 Roll Trio', 'Johnny Burnette', 'Derek Webb', 'Derek Webb;Sandra McCracken', 'Amy La Vere', 'Johnny Burnette Trio', 'The Johnny Burnette Trio', 'The Grifters', 'Deborah Allen', 'Rocky Burnette', 'Dickey Lee', 'Dorsey Burnette', 'The Gentrys']},
"47165":{"count": 170, "artists":['Steve Miller Band', 'The Oak Ridge Boys', 'Ronnie McDowell', 'Oak Ridge Boys']},
"47167":{"count": 7, "artists":['Malcolm Yelvington']},
"47187":{"count": 1, "artists":['Hayley Williams']},
"47189":{"count": 175, "artists":['Jaci Velasquez', 'Charlie Daniels Band', 'Charlie Daniels', 'Nature Lounge Club', 'The Charlie Daniels Band']},
"48001":{"count": 2, "artists":['Kinky Friedman', 'AP9']},
"48029":{"count": 298, "artists":['Butthole Surfers', 'B.H.', 'Chris Duarte', 'Rosie Flores', 'Doug Sahm Tex Mex Trip', 'Sir Douglas Quintet', 'The Sir Douglas Band', 'Doug Sahm', 'Wayne Douglas', 'Doug Sahm and the Texas Mavericks', 'Patrick Hall', 'Cave Catt Sammy', 'Christopher Cross', 'HOLLY DUNN']},
"48037":{"count": 37, "artists":['A-Alikes', 'Pocket Full Of Rocks']},
"48085":{"count": 23, "artists":['Bo Bice']},
"48095":{"count": 879, "artists":['Big B', 'Green River Ordinance', 'Marcos Hernandez', 'The Fold', 'BJ Thomas', 'Dangerous Toys', 'The Kyle Bennett Band', 'Denim', 'Opio (Souls Of Mischief)', 'Opio', 'Honeybrowne', 'Burden Brothers', 'Blue Edmondson W/ Matt Powell', 'Salim Nourallah', 'Craze', 'Homer', 'Lee Roy Parnell', 'Jessie Lee Miller', 'Ainjel Emme', 'Stratus', 'The Pacers', 'Sonny Burgess & Kings IV', 'Sonny Burgess', 'Rebeca', 'Mancy', 'Chris Watson', 'Owen Temple', 'Nerina Pallot', 'Tim Rogers', 'Colin Gilmore', 'Downfall 2012', 'Ghost of the Russian Empire', 'Jim Suhler & Monkey Beat_ Jim Suhler_ Monkey Beat', 'Kristy Kruger', 'Embodyment', 'The Service Industry', 'Patrick Ryan Clark', 'Afterglow', 'After Glow', 'Mark Monaco', 'The Addictions', 'Murder The Stout', 'The Legendary Stardust Cowboy', 'Trish Murphy', 'Hognose', 'Robyn Ludwick', 'Ken Johnson', 'Salty Dog', 'Doyle Bramhall II', 'Bramhall', 'Eye To Eye', 'Silverleaf', 'SuperHeavyGoatAss', 'Cold Blue Steel', 'Gorch Fock', 'Marty e i suoi amici', 'Eric Johnson', 'Alvis DJ', 'Alvis Wayne', 'Captain Comatose', 'Kemper Crabb', 'Gang', 'Jud Newcomb', 'The Joe Richardson Express', 'Ustad Bismillah Khan', 'Sunday Drive']},
"48113":{"count": 537, "artists":['Meat Loaf / JB', 'Meat Loaf / Kara', 'Meat Loaf featuring male vocal Roger Daltrey', 'Meat Loaf', 'Slack', 'The Secret Handshake', 'Secret Machines', 'Michelle Shocked', 'Eppu Normaali', 'Jimmie Vaughan', 'Doyle Bramhall', 'The Parties', 'The Marvelettes', 'Sam The Sham & The Pharaohs', 'Soul Retrieval', 'The Paper Chase', 'Roky Erickson & Okkervil River', 'Roky Erickson', 'Mutt', 'Trini Lopez', 'Pepe Haro', 'Michael Murphey', 'Hans Petter Hansen', 'Michael Martin Murphey', 'Jackopierce', 'Ronnie Dawson', 'B.W. Stevenson', 'Gary Myrick', 'Stephen Stills', 'HELLYEAH']},
"48121":{"count": 58, "artists":['The Riverboat Gamblers', 'Riverboat Gamblers', 'Dixie Witch', 'Lift To Experience', 'Spontaneous Combustion']},
"48141":{"count": 30, "artists":['Tom Russell & Dolores Keane', 'Kari Bremnes', 'Tom Russell & Andrew Hardin', 'Knut Reiersrud', 'Pigalle Guitar Ensemble', 'Tom Russell', 'Tom Russell & Iris Dement', 'Ait Challal', 'Iris Dement', 'Dave Van Ronk', 'Iris Dement & Kari Bremnes', 'Sondre Bratland', 'Sondre Bratland & Iris Dement', 'Dolores Keane', 'The Germs']},
"48165":{"count": 107, "artists":['Tanya Tucker / Glen Campbell', 'Tanya Tucker', 'Adolphson & Falk']},
"48189":{"count": 43, "artists":['Jimmy Dean']},
"48201":{"count": 195, "artists":['Leeland', 'B. J. THOMAS', "Thee Butcher's Orchestra", 'B.J. THOMAS', 'Awol One_ DJ Moves', 'Chris Whitley', 'Life Of Riley', 'Charalambides', 'Michael Nesmith', 'Jackviper', 'Thomas Jefferson Slave Apartments']},
"48215":{"count": 21, "artists":['Ut']},
"48245":{"count": 73, "artists":['Edgar Winter & Rick Derringer', 'Edgar Winter;The Edgar Winter Group', 'Edgar Winter;Johnny Winter', 'Edgar Winter', 'Johnny Winter']},
"48251":{"count": 29, "artists":['Pesado', 'Foster & Allen', 'Johnny Carroll and the Hot Rocks', 'Johnny Carroll_ The Hot Rocks', 'Johnny Carroll']},
"48279":{"count": 1, "artists":['Waylon Jennings']},
"48303":{"count": 245, "artists":['Delbert McClinton', 'The Crickets', 'Buddy Holly / The Fireballs', 'Buddy Holly / The Fireballs / The Fireballs', 'Buddy Holly / Bob Montgomery', 'Buddy Holly & The Crickets', 'Buddy Holly', 'Buddy Holly and The Crickets', 'Joe Ely', 'Mac Davis', 'Butch Hancock']},
"48347":{"count": 28, "artists":['Bob Luman']},
"48355":{"count": 2, "artists":['Louise Mandrell;Eric Carmen', 'Louise Mandrell']},
"48401":{"count": 15, "artists":['Claude Gray']},
"48437":{"count": 45, "artists":['Buddy Knox', 'Dale Watson']},
"48439":{"count": 236, "artists":['Trey Anastasio', 'Townes Zandt', 'Townes Van Zandt', 'Dinamics', 'Shawn Phillips', 'Kenneth McKellar', 'People Like You', 'DJ Deeon', 'Bloodrock', 'Katy Moffatt', 'King Curtis with Jack Dupree', 'King Curtis']},
"48453":{"count": 588, "artists":['Ravishankar Upadhyaya', 'Explosions In The Sky', 'Judy Dyble', 'Voxtrot', 'The Octopus Project', 'The Octopus Project + Black Moth Super Rainbow', 'Octopus Project', 'Black Moth Super Rainbow', "Biffin's Bridge", 'Lil Gangster', 'Excerpts', 'Bryan Adams', 'Eminem Instrumental', 'Yossif Ivanov_Defilharmonie_Pinchas Steinberg', 'The American Analog Set', 'Steve Schneider', 'Thanassis Moraitis', "I Love You But I've Chosen Darkness", 'Scott H. Biram', 'The Fabulous Thunderbirds', 'THE HOP LA!', 'The Band Of Heathens', 'Sound Team', 'England Dan & John Ford Coley', 'Guy Forsyth', 'Omar & The Howlers', 'Marieke', 'Grand Champeen', 'Amplified Heat', 'Zykos', 'Young Heart Attack', 'Timbuk 3', 'Golden Bear', 'Dirty Wormz', 'P.Jayachandran', 'Dancing Days', 'Bad Livers', 'The Bubble Puppy', 'Damita Jo', 'The Arm', 'Silver Scooter', 'Hundred Year Storm']},
"48459":{"count": 7, "artists":['Don Henley']},
"48461":{"count": 50, "artists":['DAN SEALS']},
"48465":{"count": 37, "artists":['Republic', 'Radney Foster']},
"48475":{"count": 32, "artists":['Guy Clark']},
"48477":{"count": 83, "artists":['Darden Smith', 'Concordia Chamber Ensemble']},
"48487":{"count": 84, "artists":['Roy Orbison']},
"48503":{"count": 34, "artists":['Mac Curtis']},
"49035":{"count": 1, "artists":['Ivy League']},
"49039":{"count": 75, "artists":['Jon Schmidt', 'Paul Cardall', 'Ned Miller']},
"49049":{"count": 17, "artists":['BLM', 'John Gorka', 'Television Personalities', 'New World Orchestra & Madrugada', 'Landing']},
"49057":{"count": 53, "artists":['Donny Osmond / Marie Osmond', 'Marie Osmond', 'Donny Osmond']},
"50007":{"count": 4, "artists":['The Cancer Conspiracy']},
"51013":{"count": 25, "artists":['Sparkadia', 'Ramsay Midwood']},
"51017":{"count": 84, "artists":['Chris Evans', 'BAM with L.E.U.', 'BAM', 'Politicks', 'Paul Miller feat. Manuel Le Saux', 'Paul Miller & Manuel Le Saux', 'Paul Miller', 'Paul Miller & Estigma', 'Cheap Thrills', 'In Clover', 'Sons Of Bill', 'David Taylor', 'Paul Miller pres. Meli', 'Ballurio']},
"51019":{"count": 16, "artists":['The Gay Blades']},
"51059":{"count": 51, "artists":['Ghoti Hook', 'emmet swimming']},
"51061":{"count": 18, "artists":['Boud Deun']},
"51087":{"count": 30, "artists":['Smokey Wilson']},
"51107":{"count": 21, "artists":['Rocket City Riot']},
"51121":{"count": 38, "artists":['DecembeRadio']},
"51143":{"count": 33, "artists":['Janis Martin']},
"51171":{"count": 13, "artists":['Danni Leigh']},
"51173":{"count": 11, "artists":['Clay Davidson']},
"51195":{"count": 3, "artists":['Roy Hall']},
"51510":{"count": 34, "artists":['Tom Paxton']},
"51590":{"count": 51, "artists":['Ricky Van Shelton']},
"51680":{"count": 11, "artists":['Ray Pillow']},
"51710":{"count": 96, "artists":['Gene Vincent & The Blue Caps', 'Gene Vincent & The Bluecaps', 'Gene Vincent And His Blue Caps', 'Gene Vincent & His Blue Caps', 'Bluejean Bop!', 'Gene Vincent']},
"51740":{"count": 108, "artists":['Swamp Dogg', 'Deborah Coleman']},
"51760":{"count": 106, "artists":['Gregor Samsa', 'Michael Franti & Spearhead / Cherine Anderson', 'Michael Franti & Spearhead / Zap Mama', 'Anti Flag', 'Michael Franti & Spearhead w/Zap Mama', 'Michael Franti & Superhead', 'Michael Franti & Spearhead', '1 Giant Leap feat. Michael Franti', 'Michael Franti', 'BT_ Tommy Stinson', 'Hey Romeo', 'Agents of Good Roots', 'A Triggering Myth']},
"51790":{"count": 1, "artists":['Things To Come']},
"51810":{"count": 47, "artists":['The White Tie Affair', 'Juice Newton']},
"53033":{"count": 718, "artists":['Shadows Fall', 'Daphne Loves Derby', 'The Classic Crime', 'Pedro The Lion', 'Neeme Jarvi', 'Big Business', 'Sunflower', 'Screaming Trees', 'The Screaming Trees', 'Gregory Haimovsky', 'Kinski', 'Lyd', 'The Supersuckers', 'Supersuckers', 'Electric Frankenstein', 'Norrkoping Symphony Orchestra', 'Estradasphere', 'The Rise', 'Tiny Vipers', 'Rosie Thomas', 'Unwed Sailor', 'Stone Gossard', 'Pete Droge', 'Judy Collins', 'Inmates', 'Zwoagsang Trellinger-Marz', 'Judy Collins and Eric Andersen', 'Fertil Miseria', 'Arthur & Yu', 'The Walkabouts', 'Walkabouts', 'The Walkabouts / Andre Heller', 'Boat', 'NME', 'Sleepy Eyes Of Death', 'Gas Huffer', 'Hypatia Lake', 'Young Fresh Fellows', 'Spoon_ Harris & Obernik', 'Jon Auer']},
"53035":{"count": 115, "artists":['MxPx', 'Blingtones']},
"53047":{"count": 17, "artists":['Mercury Rev', 'Johnny Moore', 'Johnny Moore + Skully Sims']},
"53053":{"count": 108, "artists":['The Sonics_ Charlie & The Tunas', 'Kelly Jo Phelps', 'Kelly Joe Phelps', 'Zoot Sims - Bob Brookmeyer', 'Cacique and Paje', 'John Fogerty', 'The Sonics']},
"53057":{"count": 15, "artists":['Britta Onnen', 'Mount Eerie']},
"53061":{"count": 26, "artists":['Valis']},
"53063":{"count": 87, "artists":['The Makers', "Danny O'Keefe"]},
"53067":{"count": 151, "artists":['Bikini Kill', 'Sleater-kinney', 'Sleater Kinney', 'Entombed', 'Unwound']},
"53075":{"count": 1, "artists":['Zakaria Abdulla']},
"54005":{"count": 38, "artists":['Hasil Adkins']},
"54011":{"count": 11, "artists":['Seven Day Jesus']},
"54095":{"count": 63, "artists":['Warren Smith', 'Lakker']},
"54107":{"count": 10, "artists":['The Rose Garden']},
"55017":{"count": 31, "artists":['Judy Henske']},
"55025":{"count": 57, "artists":['The United Sons Of Toil', 'Mother Earth', 'Tracy Nelson']},
"55035":{"count": 8, "artists":['Volcano Choir']},
"55073":{"count": 51, "artists":['The Invaders', 'The Invaders (Bermuda)', 'The German Art Students', 'Kenzo', 'Mary Karlzen', 'Lee Rocker']},
"55079":{"count": 117, "artists":['Steve Miller / Lol Coxhill', 'Steve Miller', 'Lights Out Asia', 'Die Kreuzen', 'Peter Mulvey', 'IfIHadAHifi', 'Jerry Harrison', 'Gordon Gano / Gordon Gano / Guy Hoffman / Pierre Henry / Brian Ritchie / Brian Ritchie', 'Gordon Gano', 'The Vocokesh']},
"55117":{"count": 1, "artists":['Bowery Boy Blue']},
"55133":{"count": 96, "artists":['The Bodeans', 'Jane Wiedlin', 'BoDeans']},
"72127":{"count": 11, "artists":['Mesmer']},

}
